####################################
### BASEMENT OFFICE AUTOMATIONS  ###
####################################

- alias: BASEMENT OFFICE - Turn on lights from motion
  mode: single
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_office_motion_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.basement_office_lights 
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.basement_office_lights
    - service: light.turn_on
      data:
        entity_id: light.ryans_desk_uplighting
        brightness_step_pct: 100
        rgb_color: [145,226,255] #Default preferred blue


- alias: BASEMENT OFFICE - Turn off lights from motion
  mode: single
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_office_motion_sensor
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: light.basement_office_lights 
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.basement_office_lights

- alias: BASEMENT OFFICE - Good morning on first movement
  mode: single
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: input_boolean.first_movement_basement_office
      to: 'on'
  condition:
    - condition: time
      after: '06:00:00'
      before: '11:30:00'
  action:
    - service: script.alexa_notify_basement_office
      data_template:
        message: "Good morning Ryan."
