############################
### BEDROOM AUTOMATIONS  ###
############################

#- alias: BEDROOM - Fan off at 7:20 a.m. if just ryan is home during the week
#  trigger:
#    - platform: time
#      at: '07:20:00'
#  condition:
#    - condition: state
#      entity_id: device_tracker.kellys_iphone
#      state: 'not_home'
#    - condition: state
#      entity_id: variable.ryan_status
#      state: 'Home'
#    - condition: time
#      weekday:
#        - mon
#        - tue
#        - wed
#        - thu
#        - fri
#  action:
#      service: homeassistant.turn_off
#      entity_id: switch.fan

########## BEDROOM LIGHT BUTTON ##########
- alias: BEDROOM - Turn on light in Bedroom (Bedroom Light Button)
  trigger:
  - event_data:
      command: button_single
      device_ieee: !secret bedroom_light_button_ieee
    event_type: zha_event
    platform: event
  condition: []
  action:
    service: script.toggle_bedroom_lights

- alias: BEDROOM - Turn on fan from light button in Bedroom (Bedroom Light Button)
  trigger:
  - event_data:
      command: button_double
      device_ieee: !secret bedroom_light_button_ieee
    event_type: zha_event
    platform: event
  condition: []
  action:
      service: switch.toggle
      entity_id: 
        - switch.fan

- alias: BEDROOM - Turn on fan and light in Bedroom (Bedroom Light Button)
  trigger:
  - event_data:
      command: button_hold
      device_ieee: !secret bedroom_light_button_ieee
    event_type: zha_event
    platform: event
  condition: []
  action:
    - service: switch.toggle
      entity_id: 
        - switch.fan
    - service: script.toggle_bedroom_lights

#####################################

############ Ryan's Bedside Button #############
- alias: BEDROOM - Turn on light in Bedroom (Ryan Button)
  trigger:
  - event_data:
      command: button_single
      device_ieee: !secret bedroom_ryans_bedside_button_ieee
    event_type: zha_event
    platform: event
  condition: []
  action:
    service: script.toggle_bedroom_lights

- alias: BEDROOM - Turn on fan in Bedroom (Ryan Button)
  trigger:
  - event_data:
      command: button_double
      device_ieee: !secret bedroom_ryans_bedside_button_ieee
    event_type: zha_event
    platform: event
  condition: []
  action:
      service: switch.toggle
      entity_id: 
        - switch.fan
#####################################


############ Motion Sensor #############
- alias: BEDROOM - Turn on Light from motion (Off after 5 min, between 10 am and 9:30pm)
  mode: restart # Restart on every motion, ensure that the light is always on
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_motion_sensor
      from: 'off'
      to: 'on'
  condition:
  # Only between the hours of 10 am and 9:30 p.m.
    - condition: time
      after: '10:00:00'
      before: '21:30:00'
  # Only if the fan is off (i.e. not in bed, sleeping)
    - condition: state
      entity_id: switch.fan
      state: 'off'
    # Check if the light is dark OR if the automation has recently been triggered
    # this allows us to skip luminance checks on restart
    - condition: or
      conditions:
      # Automation has recently been trigger by a restart within 10 min window 
      # (5 min till turn off, 5 min till lux/illuminance sensor updates)
        - condition: template
          value_template: "{{ (as_timestamp(now())-as_timestamp(states.automation.bedroom_turn_on_light_from_motion_off_after_5_min_between_10_am_and_9_30pm.attributes.last_triggered)) < 600 }}"
      # Make sure that the light level is below 10 lx
        - condition: numeric_state
          entity_id: sensor.master_bedroom_motion_sensor_illuminance
          below: 10
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom_lights
        brightness_pct: 100
    # Wait until motion goes off
    - wait_template: "{{ is_state('binary_sensor.master_bedroom_motion_sensor', 'off') }}"
    - delay:
        minutes: 5
    - service: light.turn_off
      entity_id: light.master_bedroom_lights
#####################################