############################
### BEDROOM AUTOMATIONS  ###
############################

#- alias: BEDROOM - Fan off at 7:20 a.m. if just ryan is home during the week
#  trigger:
#    - platform: time
#      at: '07:20:00'
#  condition:
#    - condition: state
#      entity_id: device_tracker.kellys_iphone
#      state: 'not_home'
#    - condition: state
#      entity_id: sensor.ryan_status
#      state: 'Home'
#    - condition: time
#      weekday:
#        - mon
#        - tue
#        - wed
#        - thu
#        - fri
#  action:
#      service: homeassistant.turn_off
#      entity_id: switch.fan


- alias: BEDROOM - Control Light and Fan (Kelly's Light Button)
  id: 62088754-7815-11ee-b962-0242ac120002
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: !secret bedroom_light_button_ieee
  condition: []
  action:
    choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'button_single' }}"
        sequence:
          - service: script.toggle_bedroom_lights
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'button_double' }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: switch.fan
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'button_hold' }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: switch.fan
          - service: script.toggle_bedroom_lights



- alias: BEDROOM - Control Light and Fan (Ryan Button)
  id: 72546ace-7815-11ee-b962-0242ac120002
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: !secret bedroom_ryans_bedside_button_ieee
  condition: []
  action:
    choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'button_single' }}"
        sequence:
          - service: script.toggle_bedroom_lights
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'button_double' }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: switch.fan




############ Motion Sensor #############
- alias: BEDROOM - Light Control from Motion (On and Off based on Motion)
  id: 7f97ba74-7815-11ee-b962-0242ac120002
  max_exceeded: silent
  trigger:
    # Trigger when motion starts
    - platform: state
      entity_id: binary_sensor.master_bedroom_motion_sensor
      from: 'off'
      to: 'on'
    # Trigger when motion has been off for 3 minutes
    - platform: state
      entity_id: binary_sensor.master_bedroom_motion_sensor
      from: 'on'
      to: 'off'
      for:
        minutes: 3
  condition:
    # Only between the hours of 10 am and 9:30 p.m.
    - condition: time
      after: '10:00:00'
      before: '21:30:00'
  action:
    - choose:
        # Turn on light if motion is detected and illuminance is low
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'on' }}"
            - condition: state
              entity_id: light.master_bedroom_lights
              state: 'off'
            - condition: numeric_state
              entity_id: sensor.master_bedroom_motion_sensor_illuminance
              below: 10
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.master_bedroom_lights
              data:
                brightness_pct: 100
        # Turn off light if no motion for 3 minutes
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'off' }}"
            - condition: state
              entity_id: light.master_bedroom_lights
              state: 'on'
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.master_bedroom_lights

# - alias: BEDROOM - Turn on Light from Motion (Off after 5 min, between 10 am and 9:30 pm)
#   id: 7f97ba74-7815-11ee-b962-0242ac120002
#   max_exceeded: silent # Hide warnings when triggered while in delay.
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.master_bedroom_motion_sensor
#       from: 'off'
#       to: 'on'
#   condition:
#     # Only if lights are off
#     - condition: state
#       entity_id: light.master_bedroom_lights 
#       state: 'off'
#     # Only between the hours of 10 am and 9:30 p.m.
#     - condition: time
#       after: '10:00:00'
#       before: '21:30:00'
#     # Make sure that the light level is below 10 lx
#     - condition: numeric_state
#       entity_id: sensor.master_bedroom_motion_sensor_illuminance
#       below: 10
#   action:
#     - service: light.turn_on
#       target:
#         entity_id: light.master_bedroom_lights
#       data:
#         brightness_pct: 100

# - alias: BEDROOM - Turn off light from no motion (3 Min)
#   id: c3a51366-6469-4df5-9a8f-ba950e15e9bc
#   max_exceeded: silent # Hide warnings when triggered while in delay.
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.master_bedroom_motion_sensor
#       from: 'on'
#       to: 'off'
#       for:
#         minutes: 3
#   condition:
#     # Only if lights are off
#     - condition: state
#       entity_id: light.master_bedroom_lights 
#       state: 'on'
#     # Only between the hours of 10 am and 9:30 p.m.
#     - condition: time
#       after: '10:00:00'
#       before: '21:30:00'
#   action:
#     - service: light.turn_off
#       target:
#         entity_id: light.master_bedroom_lights

# - alias: BEDROOM - Turn on Light from motion (Off after 5 min, between 10 am and 9:30pm)
#   id: 7f97ba74-7815-11ee-b962-0242ac120002
#   mode: restart # Restart on every motion, ensure that the light is always on
#   max_exceeded: silent 
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.master_bedroom_motion_sensor
#       from: 'off'
#       to: 'on'
#   condition:
#     # Only between the hours of 10 am and 9:30 p.m.
#     - condition: time
#       after: '10:00:00'
#       before: '21:30:00'
#     # Check if the light is dark OR if the automation has recently been triggered
#     # this allows us to skip luminance checks on restart
#     - condition: or
#       conditions:
#       # Automation has recently been trigger by a restart within 10 min window 
#       # (5 min till turn off, 5 min till lux/illuminance sensor updates)
#         - condition: template
#           value_template: "{{ (as_timestamp(now())-as_timestamp(states.automation.bedroom_turn_on_light_from_motion_off_after_5_min_between_10_am_and_9_30pm.attributes.last_triggered)) < 600 }}"
#       # Make sure that the light level is below 10 lx
#         - condition: numeric_state
#           entity_id: sensor.master_bedroom_motion_sensor_illuminance
#           below: 10
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.master_bedroom_lights
#         brightness_pct: 100
#     # Wait until motion goes off
#     - wait_template: "{{ is_state('binary_sensor.master_bedroom_motion_sensor', 'off') }}"
#     - delay:
#         minutes: 5
#     - service: light.turn_off
#       entity_id: light.master_bedroom_lights
#####################################