############################
### BEDROOM AUTOMATIONS  ###
############################

#- alias: BEDROOM - Fan off at 7:20 a.m. if just ryan is home during the week
#  trigger:
#    - platform: time
#      at: '07:20:00'
#  condition:
#    - condition: state
#      entity_id: device_tracker.kellys_iphone
#      state: 'not_home'
#    - condition: state
#      entity_id: variable.ryan_status
#      state: 'Home'
#    - condition: time
#      weekday:
#        - mon
#        - tue
#        - wed
#        - thu
#        - fri
#  action:
#      service: homeassistant.turn_off
#      entity_id: switch.fan

########## BEDROOM LIGHT BUTTON ##########

- alias: BEDROOM - Turn on light in Bedroom
  trigger:
    - platform: state
      entity_id: sensor.bedroom_light_button
      to: 'pushed'
  action:
      service: script.toggle_bedroom_lights

- alias: BEDROOM - Turn on fan from light button in Bedroom
  trigger:
    - platform: state
      entity_id: sensor.bedroom_light_button
      to: 'double'
  action:
      service: switch.toggle
      entity_id: 
        - switch.fan

- alias: BEDROOM - Turn on fan and light in Bedroom
  trigger:
    - platform: state
      entity_id: sensor.bedroom_light_button
      to: 'held'
  action:
    - service: switch.toggle
      entity_id: 
        - switch.fan
    - service: script.toggle_bedroom_lights

#####################################

############ BEDROOM FAN BUTTON #############

- alias: BEDROOM - Turn on light in Bedroom (Ryan Button)
  trigger:
    - platform: state
      entity_id: sensor.bedroom_fan_button
      to: 'pushed'
  action:
      service: script.toggle_bedroom_lights

- alias: BEDROOM - Turn on fan in Bedroom (Ryan Button)
  trigger:
    - platform: state
      entity_id: sensor.bedroom_fan_button
      to: 'double'
  action:
      service: switch.toggle
      entity_id: 
        - switch.fan
#####################################
