############################
### KITCHEN AUTOMATIONS  ###
############################

## Switch kitchen tablet to Doorbell live view when doorbell is rung
# - alias: KITCHEN - Doorbell rang, change tablet to doorbell view
#   trigger:
#   - platform: state
#     entity_id: binary_sensor.doorbell_push # Press of the doorbell
#     to: 'on'
#   - platform: state
#     entity_id: input_boolean.someone_at_front_door # Someone at front door
#     to: 'on'
#   action:
#     - service: script.turn_on_tablet_doorbell

#### Turn on Tablet if someone is in the kitchen 
# - alias: KITCHEN - Turn on tablet in kitchen, sensed motion
#   mode: restart # Restart on every motion, ensure that the light is always on
#   max_exceeded: silent # Hide warnings when triggered while in delay.
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.kitchen_motion_sensor
#       from: 'off'
#       to: 'on'
#   condition:
#     # Ignore any turn ons if the tablet was the last thing turned on
#     # only want to trigger if turned off, was the most recent triggered item
#     #- condition: template
#     #  value_template: "{{ ((state_attr('states.script.turn_on_kitchen_tablet.attributes', 'last_triggered') == none) or (state_attr('states.script.turn_off_kitchen_tablet.attributes', 'last_triggered') == none)) or (as_timestamp(now())-as_timestamp(states.script.turn_on_kitchen_tablet.attributes.last_triggered)) > (as_timestamp(now())-as_timestamp(states.script.turn_off_kitchen_tablet.attributes.last_triggered)) }}"
#     - condition: time
#       before: '01:30:00'
#       after: '06:00:00'
#   action:
#     - service: script.turn_on_kitchen_tablet
#     # Wait until motion goes off
#     - wait_template: "{{ is_state('binary_sensor.kitchen_motion_sensor', 'off') }}"
#     - delay:
#         minutes: 3
#     - service: script.turn_off_kitchen_tablet

- alias: KITCHEN - Turn off ceiling lights when no motion
  id: 86a4980e-08bc-454e-ae82-09d6d8adccff
  # mode: restart # Restart on every motion, ensure that the light is always on
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  action:
    - service: light.turn_off
      data:
        entity_id: light.kitchen_ceiling_lights

- alias: KITCHEN - Control undercabinet lights with motion
  id: 82cae31f-921a-4954-8d04-1d2577090f34
  mode: restart  # Ensures the timer restarts if motion is detected again
  max_exceeded: silent  # Suppresses warnings during delay
  trigger:
    - platform: state
      entity_id: binary_sensor.undercabinet_motion_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      to: 'off'
      for:
        minutes: 5
  action:
    - choose:
        # Turn on the light when motion is detected in kitchen area
        - conditions:
            - condition: state
              entity_id: binary_sensor.undercabinet_motion_sensor
              state: 'on'
            - condition: time
              # After 8 am
              after: '08:00:00'
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.kitchen_undercabinet_lights
        # Turn off the light when motion in all of kitchen stops for 5 minutes
        - conditions:
            - condition: state
              entity_id: binary_sensor.kitchen_motion_sensor
              state: 'off'
            - condition: state
              entity_id: binary_sensor.undercabinet_motion_sensor
              state: 'off'
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.kitchen_undercabinet_lights
