############################
### LAUNDRY AUTOMATIONS  ###
############################

- alias: LAUNDRY - Notify home laundry is done
  trigger:
    platform: template
    value_template: "{{ is_state_attr('sensor.washing_machine', 'run_completed', 'on') }}"
  condition:
    - condition: state
      entity_id: group.family 
      state: 'home'
  action:
    - service: script.alexa_notify_house
      data:
        message: "Laundry is done washing"