############################
### LAUNDRY AUTOMATIONS  ###
############################

- alias: LAUNDRY - Notify kitchen laundry is done
  trigger:
    - platform: state
      entity_id: binary_sensor.washer_wash_completed
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status 
      state: 'Home'
  action:
    - service: script.alexa_notify_kitchen
      data_template:
        message: "Laundry is done washing"


#- alias: LAUNDRY - Re-notify kitchen laundry is done after 1 hour
#  trigger:
#    platform: template
#    value_template: "{{ is_state_attr('sensor.washing_machine', 'run_completed', 'on') }}"
#    for:
#      hours: 1
#  condition:
#   - condition: state
#      entity_id: variable.family_status 
#      state: 'Home'
#  action:
#    - service: script.alexa_notify_kitchen
#      data_template:
#        message: "Reminder, laundry finished washing 1 hour ago"