############################
### LAUNDRY AUTOMATIONS  ###
############################
  
- alias: LAUNDRY - Notify house washer is done
  id: 98b90d3c-7815-11ee-b962-0242ac120002
  trigger:
  - platform: state
    entity_id: sensor.washer_washer_machine_state
    to: 'run'
    for:
      minutes: 20
  action:
    - wait_for_trigger:
      - platform: state
        entity_id: sensor.washer_washer_machine_state
        to: 'stop'
    - service: script.alexa_notify_house
      data:
        message: Your clothes have finished washing

- alias: LAUNDRY - Notify house dryer is done
  id: 9c564aa4-7815-11ee-b962-0242ac120002
  trigger:
  - platform: state
    entity_id: sensor.dryer_dryer_machine_state
    to: 'run'
    for:
      minutes: 20
  action:
    - wait_for_trigger:
      - platform: state
        entity_id: sensor.dryer_dryer_machine_state
        to: 'stop'
    - service: script.alexa_notify_house
      data:
        message: Your clothes have finished drying

- alias: LAUNDRY - Notify house dryer is in wrinklePrevent
  id: 9feaba60-7815-11ee-b962-0242ac120002
  trigger:
  - platform: state
    entity_id: sensor.dryer_dryer_machine_state
    to: 'run'
    for:
      minutes: 20
  action:
    - wait_for_trigger:
      - platform: state
        entity_id: sensor.dryer_dryer_job_state
        to: 'wrinklePrevent'
    - service: script.alexa_notify_house
      data:
        message: The dryer is in preventing wrinkles mode, time to take them out

# - alias: LAUNDRY - Notify house laundry is done after 1 hour
#   id: laundry_notify_house_laundry_is_done_after_1_hour
#   trigger:
#   - platform: state
#     entity_id: sensor.washer_washer_machine_state
#     to: 'stop'
#     for:
#       hours: 1
#   - platform: state
#     entity_id: sensor.dryer_dryer_machine_state
#     to: 'stop'
#     for:
#       minutes: 1
#   condition:
#     - condition: state
#       entity_id: sensor.family_status 
#       state: 'Home'
#   action:
#     - service: script.alexa_notify_house
#       data_template:
#         message: >
#           {% if trigger.entity_id == 'sensor.washer_washer_machine_state' %}
#           Reminder, laundry finished washing 1 hour ago
#           {% elif trigger.entity_id == 'sensor.dryer_dryer_machine_state' %}
#           Reminder, laundry finished drying 1 hour ago
#           {% endif %}

# - alias: Notify Washing maschine job state
#   description: ''
#   trigger:
#     - platform: state
#       entity_id: sensor.washer_job_state
#   condition:
#     - condition: not
#       conditions:
#         - condition: state
#           entity_id: sensor.washer_job_state
#           state: none
#   action:
#     - service: notify.notify
#       data:
#         title: 🧺 Washing machine state changed
#         message: |-
#           {% if is_state("sensor.washer_job_state", "weightSensing") %}
#             Sensing load, program may be finished at approx. {{ as_timestamp(states('sensor.washer_completion_time')) | timestamp_custom('%H:%M') }}
#           {% elif is_state("sensor.washer_job_state", "wash") %}
#             Washing, program may be finished at approx. {{ as_timestamp(states('sensor.washer_completion_time')) | timestamp_custom('%H:%M') }}
#           {% elif is_state("sensor.washer_job_state", "rinse") %}
#             Rinsing, program may be finished at approx. {{ as_timestamp(states('sensor.washer_completion_time')) | timestamp_custom('%H:%M') }}
#           {% elif is_state("sensor.washer_job_state", "spin") %}
#             Spinning, program may be finished at approx. {{ as_timestamp(states('sensor.washer_completion_time')) | timestamp_custom('%H:%M') }}
#           {% elif is_state("sensor.washer_job_state", "drying") %}
#             Drying, program may be finished at approx. {{ as_timestamp(states('sensor.washer_completion_time')) | timestamp_custom('%H:%M') }}
#           {% elif is_state("sensor.washer_job_state", "finish") %}
#             Program finished, please empty the washing machine.
#           {% else %}
#             Unknown State, please check the washing machine!
#           {% endif %}
#   mode: single