##############################
### ROOM - Laundry Room    ###
##############################
  
- alias: LAUNDRY - Notify house washer is done
  id: 98b90d3c-7815-11ee-b962-0242ac120002
  trigger:
  - trigger: state
    entity_id: sensor.washer_washer_machine_state
    to: 'run'
    for:
      minutes: 20
  action:
    - wait_for_trigger:
      - trigger: state
        entity_id: sensor.washer_washer_machine_state
        to: 'stop'
    - action: script.announce_sound
      data:
        name: "washer-done"

- alias: LAUNDRY - Notify house dryer is done
  id: 9c564aa4-7815-11ee-b962-0242ac120002
  trigger:
  - trigger: state
    entity_id: sensor.dryer_dryer_machine_state
    to: 'run'
    for:
      minutes: 20
  action:
    - wait_for_trigger:
      - trigger: state
        entity_id: sensor.dryer_dryer_machine_state
        to: 'stop'    
    - action: script.announce_sound
      data:
        name: "dryer-done"

- alias: LAUNDRY - Notify house dryer is in wrinklePrevent
  id: 9feaba60-7815-11ee-b962-0242ac120002
  trigger:
  - trigger: state
    entity_id: sensor.dryer_dryer_machine_state
    to: 'run'
    for:
      minutes: 20
  action:
    - wait_for_trigger:
      - trigger: state
        entity_id: sensor.dryer_dryer_job_state
        to: 'wrinklePrevent'
    - action: script.announce_sound
      data:
        name: "dryer-preventing-wrinkles"
