####################################
##### LIVING ROOM AUTOMATIONS   ####
####################################

# Set mode to queued so that there isn't conflicting runs when called while another is running
- alias: LIVING ROOM - Cycle AmpliPi Presets for Vinyl Player
  id: 3a57b102-8a1f-4295-a51b-6a34f9829e37
  mode: queued
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: !secret vinyl_record_button_ieee
  condition: []
  action:
    choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'button_single' }}"
        sequence:
          # Single button press, cycle through the amplipi presets
          - action: script.amplipi_cycle_preset
    
          # Intentionally set a delay to give AmpliPi until it's ready
          - wait_for_trigger:
            - trigger: state
              entity_id: script.amplipi_announce_tts
              to: 'off'
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'button_double' }}"
        sequence:
        # Double button press, go directly to default mode
          - action: input_select.select_option
            entity_id: input_select.amplipi_presets
            data_template:
              option: "Restore Default"
          # Intentionally set a delay to give AmpliPi until it's ready
          - wait_for_trigger:
            - trigger: state
              entity_id: script.amplipi_announce_tts
              to: 'off'