################################
### LIVING ROOM AUTOMATIONS  ###
################################

- alias: LIVING ROOM - Turn off living room at 11:00pm, unless occupancy detected
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_occupancy 
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.living_room_lights

- alias: LIVING ROOM - Turn off living room early (10:30pm), if living room is not being used
  trigger:
    - platform: time
      at: '22:30:00'
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_occupancy 
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_fire_tv_living_room', 'Playing') }}"h
  action:
    - service: light.turn_off
      entity_id: light.living_room_lights
