####################################
##### RYANS OFFICE AUTOMATIONS  ####
####################################

# - alias: RYANS OFFICE - Turn on lights from motion
#   mode: single
#   max_exceeded: silent # Hide warnings when triggered while in delay.
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.ryans_office_motion_sensor
#       from: 'off'
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: light.ryans_office_lights 
#       state: 'off'
#   action:
#     - service: light.turn_on
#       entity_id: light.ryans_office_lights
#     - service: light.turn_on
#       data:
#         entity_id: light.ryans_desk_uplighting
#         brightness_step_pct: 100
#         rgb_color: [145,226,255] #Default preferred blue


# - alias: RYANS OFFICE - Turn off lights from motion
#   mode: single
#   max_exceeded: silent # Hide warnings when triggered while in delay.
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.ryans_office_motion_sensor
#       from: 'on'
#       to: 'off'
#       for:
#         minutes: 5
#   condition:
#     - condition: state
#       entity_id: light.ryans_office_lights 
#       state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id: light.ryans_office_lights

- alias: RYANS OFFICE - Good morning on first movement
  id: b64c9d8c-7815-11ee-b962-0242ac120002
  mode: single
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: input_boolean.first_movement_ryans_office
      to: 'on'
  condition:
    - condition: time
      after: '06:00:00'
      before: '11:30:00'
  action:
    - service: script.alexa_notify_ryans_office
      data_template:
        message: "Good morning Ryan."
      # Turn on light, if level is below 30 lx
    - condition: numeric_state
      entity_id: sensor.ryans_office_motion_sensor_illuminance
      below: 30
    - service: light.turn_on
      continue_on_error: true
      entity_id: light.ryans_office_lights

- alias: RYANS OFFICE - Turn off lights from switch
  id: bb7b3494-7815-11ee-b962-0242ac120002
  trigger:
    - platform: state
      entity_id: switch.ryan_s_office_switch_2
      to: 'off'
  action:
    - service: light.turn_off
      continue_on_error: true
      entity_id: light.ryans_office_lights

- alias: RYANS OFFICE - Turn on lights from switch
  id: bfdbfb40-7815-11ee-b962-0242ac120002
  trigger:
    - platform: state
      entity_id: switch.ryan_s_office_switch_2
      to: 'on'
  action:
    - service: light.turn_on
      continue_on_error: true
      entity_id: light.ryans_office_lights