language: python
python:
  - "3.7"
before_install:
  - mkdir /tmp/hass
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev libavformat-dev libavdevice-dev
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config