homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  country: US
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 90
  unit_system: us_customary
  currency: USD
  time_zone: America/New_York
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.2.0/24
  allowlist_external_dirs:
    - /tmp/hass

# Enable Home Assistant Cloud functionality
cloud:

# Enable new energy mechanisms
energy:

# Logging functionality for Home Assistant
logger:
  default: error #Set to info, for more information when needed

  # logs:
  #   homeassistant.components.rest_command: debug

# Enables the Person integration for handling "home and away"
person:

# Allows links to propogate through the Home Assistant instance
my:

system_health:

# Enables the frontend
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

# Custom YAML Dashboards
lovelace:
  mode: storage
  # Add yaml dashboards      
  dashboards:
    new-dash:
      mode: yaml
      title: YAML
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: configuration/dashboards/new-dash.yaml


# Enables configuration UI
config:

http:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Support for the home-assistant mobile application
mobile_app:

# Required for camera accessibility / streaming / rtsp:
stream:

# History enabled, keeps the last two weeks
recorder:
  purge_keep_days: 14

weather:

notify:
  - name: ryan_devices
    platform: group
    services:
      - action: mobile_app_ryans_iphone_13_mini
  - name: kelly_devices
    platform: group
    services:
      - action: mobile_app_kellys_iphone_15_pro_max

media_source:

input_boolean:
  mail_arrived:
    name: Whether or not the mail has arrived
  someone_at_front_door:
    name: Whether or not someone is at the front door
  someone_at_rear_patio:
    name: Whether or not someone is at the rear patio
  someone_at_side_patio:
    name: Whether or not someone is at the side patio
  first_movement_ryans_office:
    name: First movement of the day in ryans office
  dark_outside:
    name: Whether or not it is dark outside
  front_door_deadbolt:
    # Used to create a "Lock" template to coordinate with
    # the Aqara Smart Lock in Homekit
    name: Front Door Deadbolt Status
    icon: mdi:lock

ifttt:
  key: !secret ifttt_api_key

alarm_control_panel:
  - platform: manual
    name: Alarm
    # code: !secret alarm_control_panel_code
    # Don't require the code to arm the alarm
    code_arm_required: false
    # Arm again after triggering
    disarm_after_trigger: false
    # Delay from arming and becoming armed - 30 seconds
    arming_time: 30
    # Allow time to disarm the alarm before it triggers, eg. when arriving home - 1 minute
    delay_time: 60
    # Amount of time the alarm is triggered for - 10 minutes
    trigger_time: 600
    disarmed:
      # Ensure the alarm can never be directly triggered when disarmed
      trigger_time: 0
    armed_home:
      # Leave no delay between arming -> armed
      arming_time: 0
      # Leave no delay between pending -> triggered
      delay_time: 0


homekit:
  filter:
    include_domains:
      - lock
    include_entity_globs:
      - binary_sensor.*_door_sensor
      - binary_sensor.*_windows
      - binary_sensor.*_motion_sensor
      - sensor.*_avg_temp
      - sensor.*_water_sensor_moisture
    include_entities:
      - alarm_control_panel.alarm
      - light.living_room_fireplace
      - light.living_room_desk_lamp
      - light.living_room_floor_lamp
      - light.family_room_lights
      - light.family_room_dining_table
      - light.master_bedroom_lights
      - light.outside_front_door
      - light.outside_side_patio
      - light.kitchen_ceiling_lights
      - light.kitchen_undercabinet_lights
      - light.kitchen_lights
      - light.kitchen_pendants
      - light.ryans_office_desk_lamp
      - light.ryans_office_desk_uplighting
      - light.movie_room_lights

      - camera.outside_doorbell
      - camera.outside_rear_patio
      - camera.outside_mid_yard
      - camera.outside_side_patio
      - camera.outside_under_porch

      - switch.master_bedroom_fan

      - sensor.washer_washer_machine_state
      - sensor.dryer_dryer_machine_state

      - cover.ryans_office_shades
      - cover.living_room_shades
      - cover.kitchen_window_shade_cover
      - cover.family_room_curtains
      - cover.family_room_shades

  entity_config:
    binary_sensor.front_outdoor_motion_sensor:
      linked_battery_sensor: sensor.front_outdoor_motion_sensor_battery_level
      low_battery_threshold: 30
    binary_sensor.kitchen_motion_sensor:
      linked_battery_sensor: sensor.kitchen_motion_sensor_battery_level
      low_battery_threshold: 30
    binary_sensor.laundry_motion_sensor:
      linked_battery_sensor: sensor.laundry_motion_sensor_battery_level
      low_battery_threshold: 30
    binary_sensor.master_bedroom_motion_sensor:
      linked_battery_sensor: sensor.master_bedroom_motion_sensor_battery_level
      low_battery_threshold: 30
    binary_sensor.movie_room_motion_sensor:
      linked_battery_sensor: sensor.movie_room_motion_sensor_battery_level
      low_battery_threshold: 30
    binary_sensor.ryans_office_motion_sensor:
      linked_battery_sensor: sensor.ryans_office_motion_sensor_battery_level
      low_battery_threshold: 30
    lock.front_door_deadbolt:
      linked_battery_sensor: sensor.front_door_deadbolt_battery_level
      low_battery_threshold: 30
    lock.basement_door_deadbolt:
      linked_battery_sensor: sensor.basement_door_deadbolt_battery_level
      low_battery_threshold: 30
    binary_sensor.kitchen_water_sensor_moisture:
      linked_battery_sensor: sensor.kitchen_water_sensor_battery_level
      low_battery_threshold: 30
    binary_sensor.downstairs_bathroom_water_sensor_moisture:
      linked_battery_sensor: sensor.downstairs_bathroom_water_sensor_battery_level
      low_battery_threshold: 30
    camera.outside_doorbell:
      linked_motion_sensor: binary_sensor.motion_camera_doorbell
      support_audio: True

 
#################################
##### EXTERNAL FILES BELOW ######
#################################
automation: !include_dir_merge_list automation/
# Include any dynamically created UI automations or blueprints
automation more: !include automations.yaml

binary_sensor groups: !include_dir_merge_list configuration/binary_sensor/
light: !include_dir_merge_list configuration/lights/

# Mqtt, Rest Commands, and Scripts need to be merge_named rather than merge_list
mqtt: !include_dir_merge_named configuration/mqtt/
rest_command: !include_dir_merge_named configuration/rest_command/
script: !include_dir_merge_named configuration/scripts/

sensor: !include_dir_merge_list configuration/sensor/
template: !include_dir_merge_list configuration/template/

cover: !include configuration/cover.yaml
history: !include configuration/history.yaml
input_select: !include configuration/input_select.yaml
input_datetime: !include configuration/input_datetime.yaml
input_number: !include configuration/input_number.yaml
lock: !include configuration/lock.yaml
scene: !include scenes.yaml
shell_command: !include configuration/shell_command.yaml
switch: !include configuration/switch.yaml