homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 90
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret hass_http_pass
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.2.0/24
        
  whitelist_external_dirs:
    - /tmp/hass

logger:
#  default: critical

# Enables the Person integration for handling "home and away"
person:

system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Support for the home-assistant mobile application
mobile_app:

stream:

recorder:
  purge_keep_days: 14

# Watches the folder for changes, solely for recording purposes
folder_watcher:
  - folder: /tmp/hass/

ecobee:
  api_key: !secret ecobee_api 

mqtt:
  broker: !secret mqtt_broker_ip

pi_hole:
  host: !secret pi_hole_host
  ssl: false
  verify_ssl: false

weather:
  - platform: darksky
    api_key: !secret dark_sky_api

notify:
  - platform: discord
    name: discord
    token: !secret discord_token

hue:
  bridges:
    - host: !secret hue_ip #Static IP set
      filename: mainhue.conf
      allow_unreachable: true
      allow_hue_groups: false

remote:
  - platform: harmony
    name: Harmony Hub
    host: !secret harmony_ip
    activity: Watch Shield TV

media_player:
  - platform: yamaha
    host: !secret yamaha_ip #Not a static ip
    source_ignore:
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "AirPlay"
      - "HDMI5"
      - "NET RADIO"
      - "Pandora"
      - "Rhapsody"
      - "SERVER"
      - "SiriusXM"
      - "TUNER"
      - "USB"
      - "iPod (USB)"
    source_names:
      HDMI1: "NVIDIA Shield"
      HDMI2: "Xbox One"
 # - platform: plex   # Super unreliable for some reason

wemo:
  static:
    - !secret wemo_ip_1 
    #- !secret wemo_ip_2
    #If needing to re-setup, launch HASS without switch ON -- plug in Wemo, then restart again
    #almost like you need the switch to be offline when first setting up
    #Still not statically set on network, but required without ports

camera:
  - platform: generic
    name: Rear Porch Camera
    still_image_url: !secret unifi_rear_porch_camera_still
    stream_source: !secret unifi_rear_porch_camera_source
    verify_ssl: false
  - platform: generic
    name: Front Door Camera
    still_image_url: !secret unifi_front_door_camera_still
    stream_source: !secret unifi_front_door_camera_source
    verify_ssl: false
  - platform: generic
    name: Living Room Camera
    still_image_url: !secret unifi_living_room_camera_still
    stream_source: !secret unifi_living_room_camera_source
    verify_ssl: false
  - platform: generic
    name: Garage Camera
    still_image_url: !secret unifi_garage_camera_still
    stream_source: !secret unifi_garage_camera_source
    verify_ssl: false
  - platform: generic
    name: Doorbell Camera
    still_image_url: !secret unifi_doorbell_camera_still
    stream_source: !secret unifi_doorbell_camera_source
    verify_ssl: false

# Custom HACS variable integation
# https://github.com/rogro82/hass-variables
# Changed from input_select_dropdown to variables for being
# able to keep states through restarts
variable:
  ryan_status:
    restore: true
  kelly_status:
    restore: true
  family_status:
    restore: true
  tautilli_data:
    value: ""
    restore: true

binary_sensor:
  - platform: template
    sensors:
      device_critical:
        value_template: >-
          "{{ is_state('states.sensor.garage_camera','Offline')
          or is_state('states.sensor.hdhomerun_extend', 'Offline')
          or is_state('states.sensor.hue_bridge', 'Offline')
          or is_state('states.sensor.kitchen_tablet', 'Offline')
          or is_state('states.sensor.logitech_harmony_hub', 'Offline')
          or is_state('states.sensor.smartthings_hub', 'Offline')
          or is_state('states.sensor.synology_nas', 'Offline')
          or is_state('states.sensor.yamaha_receiver', 'Offline') }}"
        friendly_name: 'Device Critical'
  - platform: unifiprotect
  - platform: bhyve

unifiprotect:
  host: 192.168.1.2
  username: !secret unifiprotect_user
  password: !secret unifiprotect_pass
  port: 7443

bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password

switch:
  - platform: bhyve

#################################
##### EXTERNAL FILES BELOW ######
#################################
group: !include configuration/groups.yaml

automation: !include_dir_merge_list automation/

lock: !include configuration/locks.yaml

light: !include configuration/lights.yaml

history: !include configuration/history.yaml

sensor: !include configuration/sensor.yaml

script: !include configuration/script.yaml

input_select: !include configuration/input_select.yaml

shell_command: !include configuration/shell_command.yaml
