homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 90
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret hass_http_pass
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.2.0/24
        
  whitelist_external_dirs:
    - /tmp/hass

logger:
#  default: critical

media_player:
  - platform: yamaha
    host: !secret yamaha_ip #Not a static ip
    source_ignore:
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "AirPlay"
      - "HDMI5"
      - "NET RADIO"
      - "Pandora"
      - "Rhapsody"
      - "SERVER"
      - "SiriusXM"
      - "TUNER"
      - "USB"
      - "iPod (USB)"
    source_names:
      HDMI1: "NVIDIA Shield"
      HDMI2: "Xbox One"
 # - platform: plex   # Super unreliable for some reason

wemo:
  static:
    - !secret wemo_ip_1 
    #- !secret wemo_ip_2
    #If needing to re-setup, launch HASS without switch ON -- plug in Wemo, then restart again
    #almost like you need the switch to be offline when first setting up
    #Still not statically set on network, but required without ports

# Enables the Person integration for handling "home and away"
# new as of 0.97+?
person:

system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_keep_days: 14

# View all events in a logbook
logbook:

# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret dark_sky_api

# Text to speech
tts:
  platform: google_translate

# This is now required apparently on 0.60.0+ for multiple hue bridges
hue:
  bridges:
    - host: !secret hue_ip # Not a static IP
      filename: mainhue.conf
      allow_unreachable: true
      allow_hue_groups: false

camera:
  - platform: generic
    name: Rear Porch Camera
    still_image_url: !secret unifi_rear_porch_camera_still
    stream_source: !secret unifi_rear_porch_camera_source
    verify_ssl: false
  - platform: generic
    name: Front Door Camera
    still_image_url: !secret unifi_front_door_camera_still
    stream_source: !secret unifi_front_door_camera_source
    verify_ssl: false
  - platform: generic
    name: Living Room Camera
    still_image_url: !secret unifi_living_room_camera_still
    stream_source: !secret unifi_living_room_camera_source
    verify_ssl: false
  - platform: generic
    name: Garage Camera
    still_image_url: !secret unifi_garage_camera_still
    stream_source: !secret unifi_garage_camera_source
    verify_ssl: false

stream:

ecobee:
  api_key: !secret ecobee_api 

mqtt:
  broker: !secret mqtt_broker_ip

smartthinq:
  token: !secret smartthinq_api
  region: US
  language: en-US

pi_hole:
  host: !secret pi_hole_host
  ssl: false
  verify_ssl: false

shell_command:
  unifi_ap_light_on: !secret unifi_ap_light_on #bash scripts/unifiAPLED.sh -i <ip_address> -s on
  unifi_ap_light_off: !secret unifi_ap_light_off #bash scripts/unifiAPLED.sh -i <ip_address> -s off
  clear_video_directory: !secret clear_video_directory
  convert_camera_recording: !secret convert_camera_recording

# Custom HACS variable integation
# https://github.com/rogro82/hass-variables
# Changed from input_select_dropdown to variables for being
# able to keep states through restarts
variable:
  ryan_status:
    #value: "Unknown"
    restore: true
  kelly_status:
    #value: "Unknown"
    restore: true
  tautilli_data:
    value: ""
    restore: true

binary_sensor:
  - platform: template
    sensors:
      device_critical:
        value_template: >-
          "{{ is_state('states.sensor.garage_camera','Offline')
          or is_state('states.sensor.hdhomerun_extend', 'Offline')
          or is_state('states.sensor.hue_bridge', 'Offline')
          or is_state('states.sensor.kitchen_tablet', 'Offline')
          or is_state('states.sensor.logitech_harmony_hub', 'Offline')
          or is_state('states.sensor.smartthings_hub', 'Offline')
          or is_state('states.sensor.synology_nas', 'Offline')
          or is_state('states.sensor.yamaha_receiver', 'Offline') }}"
        friendly_name: 'Device Critical'
  ## Front Door Motion Sensor
  - platform: mqtt
    name: Front Door Motion Sensor
    state_topic: "/camera/motion/front_door"
    payload_on: 'ON'
    payload_off: 'OFF'
    device_class: motion
  - platform: mqtt
    name: Rear Porch Motion Sensor
    state_topic: "/camera/motion/rear_porch"
    payload_on: 'ON'
    payload_off: 'OFF'
    device_class: motion


notify:
  - platform: discord
    name: discord
    token: !secret discord_token

folder_watcher:
  - folder: /tmp/hass/

# Support for the home-assistant mobile application
mobile_app:

#External files
group: !include groups.yaml

automation: !include_dir_merge_list automation

lock: !include locks.yaml

light: !include lights.yaml

history: !include history.yaml

sensor: !include sensor.yaml

script: !include script.yaml


#### Unused Integration below, either changed or moved to an integration in the UI

# Moved to integrations also covers device_tracker:
#unifi:


# Moved to integration
#  - platform: huesensor

#  - platform: template
#    sensors:
#      basement_temperature:
#        friendly_name: 'Basement Temperature'
#        value_template: "{{ ((states.sensor.basement_laundry_sensor.attributes.temperature | float * (9 / 5)) + 32) | round(1) }}"
#       unit_of_measurement: °F

#binary_sensor:
#  - platform: huesensor
