homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 90
  unit_system: imperial
  time_zone: America/New_York
  # Folders / files for customize: plugin
  # Mainly for changing names, icons, etc...
  customize: !include_dir_merge_named customize
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret hass_http_pass
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.2.0/24
  allowlist_external_dirs:
    - /tmp/hass

# Enable Home Assistant Cloud functionality
cloud:

# Logging functionality for Home Assistant
logger:
#  default: critical

# Enables the Person integration for handling "home and away"
person:

system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Support for the home-assistant mobile application
mobile_app:

# Required for camera accessibility / streaming / rtsp:
stream:

# History enabled, keeps the last two weeks
recorder:
  purge_keep_days: 14

# Watches the folder for changes, solely for recording purposes
folder_watcher:
  - folder: /tmp/hass/

weather:

# Enable functionality for Discord mobile notification alerts
notify:
  - platform: discord
    name: discord
    token: !secret discord_token

media_player:
  - platform: yamaha
    host: !secret yamaha_ip #Not a static ip
    source_ignore:
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "AirPlay"
      - "HDMI5"
      - "NET RADIO"
      - "Pandora"
      - "Rhapsody"
      - "SERVER"
      - "SiriusXM"
      - "TUNER"
      - "USB"
      - "iPod (USB)"
    source_names:
      HDMI1: "NVIDIA Shield"
      HDMI2: "Xbox One"
 # - platform: plex   # Super unreliable for some reason
  - platform: smartir
    name: Living room TV
    unique_id: living_room_tv
    device_code: 1400
    controller_data: remote.living_room_remote
    power_sensor: binary_sensor.tv_power

wemo:
  static:
    - !secret wemo_ip_1 
    #- !secret wemo_ip_2
    #If needing to re-setup, launch HASS without switch ON -- plug in Wemo, then restart again
    #almost like you need the switch to be offline when first setting up
    #Still not statically set on network, but required without ports

camera:
  - platform: generic
    name: Rear Porch Camera
    still_image_url: !secret unifi_rear_porch_camera_still
    stream_source: !secret unifi_rear_porch_camera_source
    verify_ssl: false
  - platform: generic
    name: Front Door Camera
    still_image_url: !secret unifi_front_door_camera_still
    stream_source: !secret unifi_front_door_camera_source
    verify_ssl: false
  - platform: generic
    name: Living Room Camera
    still_image_url: !secret unifi_living_room_camera_still
    stream_source: !secret unifi_living_room_camera_source
    verify_ssl: false
  - platform: generic
    name: Garage Camera
    still_image_url: !secret unifi_garage_camera_still
    stream_source: !secret unifi_garage_camera_source
    verify_ssl: false
  - platform: generic
    name: Doorbell Camera
    still_image_url: !secret unifi_doorbell_camera_still
    stream_source: !secret unifi_doorbell_camera_source
    verify_ssl: false

# Custom HACS variable integation
# https://github.com/rogro82/hass-variables
# Changed from input_select_dropdown to variables for being
# able to keep states through restarts
variable:
  ryan_status:
    restore: true
  kelly_status:
    restore: true
  family_status:
    restore: true
  tautilli_data:
    value: ""
    restore: true

unifiprotect:
  host: !secret unifiprotect_ip
  username: !secret unifiprotect_user
  password: !secret unifiprotect_pass
  port: !secret unifiprotect_port

bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password

smartir:


climate:
  - platform: smartir
    name: Living Room AC
    unique_id: living_room_ac
    device_code: 2040
    controller_data: remote.living_room_remote
    power_sensor: binary_sensor.living_room_ac_power

# Z-Wave USB0, Zigbee USB1 (Manually upgraded firmware on USB stick)
zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key
  
#################################
##### EXTERNAL FILES BELOW ######
#################################
automation: !include_dir_merge_list automation/

light: !include configuration/lights.yaml

history: !include configuration/history.yaml

sensor: !include configuration/sensor.yaml

script: !include configuration/script.yaml

input_select: !include configuration/input_select.yaml

shell_command: !include configuration/shell_command.yaml

binary_sensor: !include configuration/binary_sensor.yaml

switch: !include configuration/switch.yaml

cover: !include configuration/cover.yaml