################################################
### PERSON_STATUS CONFIGURATION / AUTOMATION ###
################################################

# Changing all modes in here to parallel

# Occasionally, there would be incorrect "Just Left" "Just Arrived"
# and never go to "Home". Assuming this may be from not executing parellel
# tasks for one of us to mark as home when both arriving, maybe leaving

- alias: PERSON - Mark person as just arrived
  id: 20d463de-7815-11ee-b962-0242ac120002
  mode: parallel
  trigger:
    - trigger: state
      entity_id: person.ryan
      from: 'not_home'
      to: 'home'
    - trigger: state
      entity_id: person.kelly
      from: 'not_home'
      to: 'home'
  action:
    - action: variable.update_sensor
      data_template:
        value: >
          {% if trigger.entity_id == 'person.ryan' %}
            {% if states.sensor.ryan_status.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.sensor.kelly_status.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %} 
      target:
        entity_id: >
          {% if trigger.entity_id == 'person.ryan' %}
            sensor.ryan_status
          {% else %}
            sensor.kelly_status
          {% endif %}


- alias: PERSON - Mark person as home
  id: 274c2d00-7815-11ee-b962-0242ac120002
  mode: parallel
  trigger:
    - trigger: state
      entity_id: sensor.ryan_status
      to: 'Just Arrived'
      for:
        minutes: 10
    - trigger: state
      entity_id: sensor.kelly_status
      to: 'Just Arrived'
      for:
        minutes: 10
    - trigger: state
      entity_id: sensor.ryan_status
      from: 'Just Left'
      to: 'Just Arrived'
    - trigger: state
      entity_id: sensor.kelly_status
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - action: variable.update_sensor
      data:
        value: Home
      target:
        entity_id: >
          {% if trigger.entity_id == 'sensor.ryan_status' %}
            sensor.ryan_status
          {% else %}
            sensor.kelly_status
          {% endif %}
 
- alias: PERSON - Mark person as just left
  id: 2cbe0f1a-7815-11ee-b962-0242ac120002
  mode: parallel
  trigger:
    - trigger: state
      entity_id: person.ryan
      from: 'home'
      to: 'not_home'
    - trigger: state
      entity_id: person.kelly
      from: 'home'
      to: 'not_home'
  action:
    - action: variable.update_sensor
      data:
        value: Just Left
      target:
        entity_id: >
          {% if trigger.entity_id == 'person.ryan' %}
            sensor.ryan_status
          {% else %}
            sensor.kelly_status
          {% endif %}
 
- alias: PERSON - Mark person as not_home
  id: 31b7c1e6-7815-11ee-b962-0242ac120002
  mode: parallel
  trigger:
    - trigger: state
      entity_id: sensor.ryan_status
      to: 'Just Left'
      for:
        minutes: 10
    - trigger: state
      entity_id: sensor.kelly_status
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - action: variable.update_sensor
      data:
        value: Away
      target:
        entity_id: >
          {% if trigger.entity_id == 'sensor.ryan_status' %}
            sensor.ryan_status
          {% else %}
            sensor.kelly_status
          {% endif %}
 
- alias: PERSON - Mark person as extended not_home
  id: 36b4266c-7815-11ee-b962-0242ac120002
  mode: parallel
  trigger:
    - trigger: state
      entity_id: sensor.ryan_status
      to: 'Away'
      for:
        hours: 24
    - trigger: state
      entity_id: sensor.kelly_status
      to: 'Away'
      for:
        hours: 24
  action:
    - action: variable.update_sensor
      data:
        value: Extended Away
      target:
        entity_id: >
          {% if trigger.entity_id == 'sensor.ryan_status' %}
            sensor.ryan_status
          {% else %}
            sensor.kelly_status
          {% endif %}
        
        
- alias: PERSON - Mark Family as Away if both go from Just Left to Away
  id: 3b6672fa-7815-11ee-b962-0242ac120002
  mode: parallel
  trigger:
    - trigger: state
      entity_id: sensor.ryan_status
      from: 'Just Left'
      to: 'Away'
    - trigger: state
      entity_id: sensor.kelly_status
      from: 'Just Left'
      to: 'Away'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.ryan_status
          state: 'Away'
        - condition: state
          entity_id: sensor.ryan_status
          state: 'Extended Away' 
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.kelly_status
          state: 'Away'
        - condition: state
          entity_id: sensor.kelly_status
          state: 'Extended Away' 
  action:
    - action: variable.update_sensor
      data:
        value: Away
      target:
        entity_id: sensor.family_status

- alias: PERSON - Mark Family as Home if someone goes from Away to Just Arrived
  id: 4126d874-7815-11ee-b962-0242ac120002
  mode: parallel
  trigger:
    - trigger: state
      entity_id: sensor.ryan_status
      from: 'Away'
      to: 'Just Arrived'
    - trigger: state
      entity_id: sensor.ryan_status
      from: 'Extended Away'
      to: 'Just Arrived'
    - trigger: state
      entity_id: sensor.kelly_status
      from: 'Away'
      to: 'Just Arrived'
    - trigger: state
      entity_id: sensor.kelly_status
      from: 'Extended Away'
      to: 'Just Arrived'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.ryan_status
        state: 'Just Arrived'
      - condition: state
        entity_id: sensor.ryan_status
        state: 'Home'
      - condition: state
        entity_id: sensor.kelly_status
        state: 'Just Arrived'
      - condition: state
        entity_id: sensor.kelly_status
        state: 'Home'
  action:
    - action: variable.update_sensor
      data:
        value: Home
      target:
        entity_id: sensor.family_status
