###############################
####### Scene - AmpliPi  ######
###############################

# Announce which scene has been applied utilizing the ability
# to listen to all scenes being activated, and utilizing any that
# start with "scene.amplipi"
#  - Only after 9:00 a.m.
- alias: "SCENE - AmpliPi Announce What Scene Was Set"
  id: 99896361-e393-4f21-82d8-37df61cfb6cd

  trigger:
    - trigger: event
      event_type: call_service
      event_data:
        domain: scene
        service: turn_on

  condition:

      # Only after 9:00 a.m.
    - condition: time
      after: "09:00:00"

    - condition: template

      # Sometimes the scene that comes through is a list of scenes
      # and sometimes it's an individual one, this is to accomodate
      # for that. As well as only match with scenes that start with 
      # "amplipi"
      value_template: >
        {% set ids = trigger.event.data.service_data.entity_id %}
        {% if ids is string %}
          {{ ids.startswith('scene.amplipi') }}
        {% elif ids is iterable and ids is not string %}
          {{ ids | select('match', '^scene\.amplipi') | list | length > 0 }}
        {% else %}
          false
        {% endif %}


  action:
    # Currently there is no way to determine when is scene is done applying
    # For now, we will put a 3 second delay to allow the devices to be set
    # in Home Assistant without messing them up since an announcement is
    # a temporary "Source"

    # 10 second delay
    - delay: "00:00:10"

    # Send an announcement to the AmpliPi using the Scene's name. Converting
    # any dashes to spaces and removing and "-"
    - action: script.amplipi_announce_tts
      data:
        message: >
          {% set ids = trigger.event.data.service_data.entity_id %}
          {% if ids is string %}
            {% set ent = ids %}
          {% elif ids is iterable and (ids | length > 0) %}
            {% set ent = (ids | select('match', '^scene\.amplipi') | list | first) %}
          {% else %}
            {% set ent = None %}
          {% endif %}

          {{ (state_attr(ent, 'friendly_name') or 'Unknown')
              .replace('-', ' ')
              | title }} scene ready.
        volume: 0.7