##################################
##### GOING LIGHT AUTOMATIONS ####
##################################
- alias: GOING LIGHT - Turn off lights outside when light outside
  id: 54332a62-7815-11ee-b962-0242ac120002
  trigger:
    - platform: state
      entity_id: input_boolean.dark_outside
      to: 'off'
  condition:
    # Only proceed, if we haven't used this in the last 12 hours
    - condition: template 
      value_template: "{{ (state_attr('states.automation.going_light_turn_off_lights_outside_when_light_outside.attributes', 'last_triggered') == none) or ((as_timestamp(now())-as_timestamp(states.automation.going_light_turn_off_lights_outside_when_light_outside.attributes.last_triggered)) > 43200) }}"
    # Only after 5 am and before 11am
    - condition: time
      after: '05:00:00'
      before: '11:00:00'
  action:
    - service: light.turn_off
      continue_on_error: true
      entity_id: light.outside_lights

- alias: GOING LIGHT - Open kitchen blind when it's getting light outside
  id: 4998a9e4-f851-4ddc-8b08-be079f42ff11
  trigger:
    - platform: state
      entity_id: input_boolean.dark_outside
      to: "off"
  action:
    - service: cover.open_cover
      entity_id: cover.kitchen_window_shade_cover