#################################
##### GOING DARK AUTOMATIONS ####
#################################

#   Turn on Family Room Lights, Outside to 100%
#   turn off unneeded lights if nobody is home
- alias: GOING DARK - Turn on lights when outside gets dark
  id: 4c3cbda0-7815-11ee-b962-0242ac120002
  trigger:
    # Make sure that it's dark outside
    - platform: state
      entity_id: input_boolean.dark_outside
      to: "on"
  condition:
    # Only proceed, if we haven't used this in the last 12 hours
    - condition: template
      value_template: >-
        {{
        (state_attr('states.automation.going_dark_turn_on_lights_when_outside_gets_dark.attributes',
        'last_triggered') == none) or
        ((as_timestamp(now())-as_timestamp(states.automation.going_dark_turn_on_lights_when_outside_gets_dark.attributes.last_triggered))
        > 43200) }}
  action:
    - service: light.turn_on
      continue_on_error: true
      data:
        entity_id:
          - light.family_room_lights
          - light.kitchen_lights
          - light.living_room_lights
        transition: 10
    - service: light.turn_on
      continue_on_error: true
      data:
        entity_id:
          - light.outside_lights
        brightness_pct: 100
        transition: 2
    # Only proceed if someone is not home
    # turn off lights that we don't want to leave on
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
    - service: light.turn_off
      continue_on_error: true
      entity_id:
        - light.kitchen_ceiling_lights

- alias: GOING DARK - Close all curtains and shades when it's getting dark
  id: 5f9f9787-3108-4c69-997b-ba7fbdee9285
  trigger:
    # Make sure that it's dark outside
    - platform: state
      entity_id: input_boolean.dark_outside
      to: "on"
  action:
    - service: cover.close_cover
      entity_id: cover.house_covers