##################################
##### GOING LIGHT AUTOMATIONS ####
##################################
- alias: GOING LIGHT - Turn off lights outside when light outside
  trigger:
    # Make sure that it's dark outside
    - platform: state
      entity_id: input_boolean.dark_outside
      to: 'off'
  condition:
    # Only proceed, if we haven't used this in the last 12 hours
    - condition: template 
      value_template: "{{ (state_attr('states.automation.going_light_turn_off_lights_outside_when_light_outside.attributes', 'last_triggered') == none) or ((as_timestamp(now())-as_timestamp(states.automation.going_light_turn_off_lights_outside_when_light_outside.attributes.last_triggered)) > 43200) }}"
    # Only after 4 pm and before 9pm
    - condition: time
      after: '05:00:00'
      before: '11:00:00'
  action:
    - service: light.turn_off
      entity_id: light.outside_lights