#################################
##### GOING DARK AUTOMATIONS ####
#################################


# Darker than 15 Lux Outsdie 
# - Turn on Living room lights to 90%, Outside to 100%
#   turn off unneeded lights if nobody is home: center lamp,
#   bookcase lamp, undercabinet kitchen lights
- alias: GOING DARK - Turn on lights when outside gets dark
  trigger:
    # Make sure that the light level is below 10 lx
    - platform: numeric_state
      entity_id: sensor.front_outdoor_motion_sensor_illuminance
      below: 15
  condition:
    # Only proceed, if we haven't used this in the last 12 hours
    - condition: template 
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.automation.going_dark_turn_on_lights_when_outside_gets_dark.attributes.last_triggered)) > 43200 }}"
    # Only after 4 pm and before 9pm
    - condition: time
      after: '16:00:00'
      before: '21:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.living_room_lights
          - light.kitchen_lights
        brightness_pct: 90
        transition: 10
    - service: light.turn_on
      data:
        entity_id: 
          - light.outside_lights
        brightness_pct: 100
        transition: 2
      # Only proceed if someone is not home
      # turn off lights that we don't want to leave on
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
    - service: light.turn_off
      entity_id: 
        - light.living_room_center_lamp
        - light.living_room_bookcase_lamp
        - light.kitchen_undercabinet_lights