################################################
### DRYER_STATUS CONFIGURATION / AUTOMATION ####
################################################

# 2/26/21 not in use

- alias: Set dryer active when vibrating for 5 minutes
  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_vibration_sensor
      to: "on"
      for:
        minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dryer_status
        state: Idle
      - condition: state
        entity_id: input_select.dryer_status
        state: Done
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: Running


- alias: Set dryer to done when vibration stops for 2 minutes
  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_vibration_sensor
      from: 'on'
      to: "off"
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_select.dryer_status
      state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: Done


- alias: Set Dryer to Idle when Done for 10 minutes
  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_vibration_sensor
      to: "off"
      for:
        minutes: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dryer_status
        state: Running
      - condition: state
        entity_id: input_select.dryer_status
        state: Done
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: Idle