################################
### LOGIC - Harmony Hub      ###
################################

- alias: HARMONY - Harmony Hub input_select
  id: 106148a0-7815-11ee-b962-0242ac120002
  trigger:
    trigger: state
    entity_id: input_select.harmony_hub
    from: 'Select Input'
  action:
    - action: script.harmony_set_activity
      data:
        activity: >
          {% if states('input_select.harmony_hub') == 'Power Off' %}
            PowerOff
          {% else %}
            {{ states('input_select.harmony_hub') }}
          {% endif %}
    - action: input_select.select_option
      entity_id: input_select.harmony_hub
      data:
        option: "Select Input"
