- alias: HARMONY - Harmony Hub input_select
  id: 106148a0-7815-11ee-b962-0242ac120002
  trigger:
    platform: state
    entity_id: input_select.harmony_hub
    from: 'Select Input'
  action:
    - service: >
          {% if states.input_select.harmony_hub.state == "Watch Shield TV" %}
            script.harmony_shield_tv
          {% elif states.input_select.harmony_hub.state == "Play PS4" %}
            script.harmony_ps4
          {% elif states.input_select.harmony_hub.state == "Play Switch" %}
            script.harmony_switch
          {% elif states.input_select.harmony_hub.state == "Power Off" %}
            script.harmony_poweroff
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony_hub
      data_template:
        option: "Select Input"
