####################################
### ALERT / DISCORD AUTOMATIONS  ###
####################################

########################################
######### Companion App Below ##########
########################################

- alias: ALERT - Doorbell rang, notify Mobile App and House
  id: 287a519e-7814-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: binary_sensor.doorbell_push # Press of the doorbell
      from: "off"
      to: "on"
  action:
    - action: script.amplipi_announce_media
      data:
        type: doorbell-sound
        where: home_alert
    - delay: "00:00:02" # Wait 2 seconds so we don't get their finger in the camera
    - action: notify.ryan_devices
      data:
        title: Doorbell Rang
        message: ""
        data:
          ttl: 0
          priority: high
          image: "/api/camera_proxy/camera.outside_doorbell" # Captures image immediately, sends via notification
          url: /lovelace/camera_view

- alias: ALERT - When a critical device goes offline to mobile app
  id: 3039b6f4-7814-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: 
        - sensor.hdhomerun_extend
        - sensor.kitchen_tablet
        - sensor.logitech_harmony_hub
        - sensor.synology_nas
        - sensor.yamaha_reciever
        - sensor.doorbell_camera
        - sensor.side_patio_camera
        - sensor.rear_patio_camera
      from: 'Online'
      to: 'Offline'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
         value_template: 
          {% if states.automation.alert_when_a_critical_device_goes_offline is not none %}
            {% if as_timestamp(now()) | int - as_timestamp(states.automation.alert_when_a_critical_device_goes_offline.attributes.last_triggered) | int > 3600 %} 
              true
            {% else %} 
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
  action:
    action: notify.ryan_devices
    data:
      title: "Critical Device Alert"
      message: "{{trigger.to_state.attributes.friendly_name}} has gone offline."
      data:
        ttl: 0
        priority: high
        clickAction: "/lovelace/devices_view"


- alias: ALERT - HA Persistent Notifications to Mobile App
  id: 36810da0-7814-11ee-b962-0242ac120002
  trigger:
  - event_data:
      domain: persistent_notification
      service: create
    event_type: call_service
    trigger: event
  condition: []
  action:
    action: notify.ryan_devices
    data:
      title: "{{trigger.event.data.service_data.title}}"
      message: "{{trigger.event.data.service_data.message}}"

- alias: ALERT - HA Update Available to Mobile App
  id: 416cb260-ee0b-11ee-a951-0242ac120002
  trigger:
    - trigger: state
      entity_id: binary_sensor.home_assistant_website_update_available
      from: 'off'
      to: 'on'
  action:
    action: notify.ryan_devices
    data:
      title: "New Version of HASS Available"
      message: "Release Notes for {{ states('sensor.home_assistant_website') }}: {{ state_attr('sensor.home_assistant_website', 'release_notes') }}"   
      data:
        ttl: 0
        priority: high
        url: "{{ state_attr('sensor.home_assistant_website', 'release_notes') }}"

- alias: ALERT - PiHole Update Available to Mobile App
  id: d1a268a0-f2d6-11ee-a951-0242ac120002
  trigger:
    - trigger: state
      entity_id: update.pi_hole_ftl_update_available
      from: 'off'
      to: 'on'
  action:
    action: notify.ryan_devices
    data:
      title: "New Version of Pi-Hole FTL Available"
      message: "New Version: {{ state_attr('update.pi_hole_ftl_update_available', 'latest_version') }} | Installed: {{ state_attr('update.pi_hole_ftl_update_available', 'installed_version') }}"   
      data:
        ttl: 0
        priority: high
        url: "{{ state_attr('update.pi_hole_ftl_update_available', 'release_url') }}"

- alias: ALERT - UPS Power State
  id: b5af027a-ede3-4b55-9fe3-4cdca51c3c80
  mode: queued
  trigger:
    - trigger: template
      value_template: "{{ 'On Battery' in states('sensor.ups_status') }}"
      id: battery
      for: "00:00:30"
    - trigger: state
      entity_id: sensor.ups_status
      to: "Online"
      id: online
      for: "00:00:30"
  action:
    - choose:
        - conditions: "{{ trigger.id == 'battery' }}"
          sequence:
            - action: notify.ryan_devices
              data:
                title: "Home Power Outage"
                message: >
                  UPS Battery Runtime: {{ states('sensor.ups_battery_runtime') }} minutes
        - conditions: "{{ trigger.id == 'online' }}"
          sequence:
            - action: notify.ryan_devices
              data:
                title: "Home Power Online"
                message: "Power has returned"



- alias: ALERT - Low battery on sensor, notify Mobile App
  id: 3c4cf9b0-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: numeric_state
      entity_id:
        - sensor.kellys_office_rear_window_sensor_battery_level
        - sensor.kellys_office_side_window_sensor_battery_level
        - sensor.upstairs_bathroom_window_sensor_battery_level
        - sensor.ryans_office_rear_window_sensor_battery_level
        - sensor.ryans_office_side_window_sensor_battery_level
        - sensor.master_bedroom_front_window_sensor_battery_level
        - sensor.master_bedroom_side_window_sensor_battery_level
        - sensor.guest_room_front_window_sensor_battery_level
        - sensor.guest_room_side_window_sensor_battery_level
        - sensor.living_room_front_window_sensor_battery_level
        - sensor.living_room_side_window_1_sensor_battery_level
        - sensor.living_room_side_window_2_sensor_battery_level
        - sensor.living_room_rear_window_sensor_battery_level
        - sensor.half_bath_window_sensor_battery_level
        - sensor.kitchen_window_sensor_battery_level
        - sensor.family_room_front_window_1_sensor_battery_level
        - sensor.family_room_front_window_2_sensor_battery_level
        - sensor.family_room_side_window_1_sensor_battery_level
        - sensor.family_room_side_window_2_sensor_battery_level
        - sensor.family_room_rear_window_1_sensor_battery_level
        - sensor.family_room_rear_window_2_sensor_battery_level
        - sensor.family_room_rear_window_3_sensor_battery_level
        - sensor.laundry_room_window_sensor_battery_level
        - sensor.movie_room_window_sensor_battery_level
        - sensor.bedroom_light_button_battery_level
        - sensor.ryans_bedside_button_battery_level
        - sensor.basement_door_deadbolt_battery_level
        - sensor.front_door_deadbolt_battery_level
        - sensor.kitchen_motion_sensor_battery_level
        - sensor.laundry_motion_sensor_battery_level
        - sensor.ryans_office_motion_sensor_battery_level
        - sensor.media_room_motion_sensor_battery_level
        - sensor.master_bedroom_motion_sensor_battery_level
        - sensor.front_outdoor_motion_sensor_battery_level
        - sensor.basement_door_sensor_battery_level
        - sensor.front_door_sensor_battery_level
        - sensor.ryans_office_door_sensor_battery_level
        - sensor.porch_slider_sensor_battery_level
        - sensor.family_room_slider_battery_level
        - sensor.kitchen_water_sensor_battery_level
        - sensor.downstairs_bathroom_water_sensor_battery_level
        - sensor.lawn_mower_sensor_battery_level
      below: 30
  action:
    - action: notify.ryan_devices
      data:
        title: Sensor Battery Low
        message: "{{trigger.from_state.attributes.friendly_name}} is low"
        data:
          url: /lovelace/devices_view

- alias: ALERT - Sensor went unavailable, notify Mobile App
  id: 43a40884-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.kellys_office_rear_window_sensor
        - binary_sensor.kellys_office_side_window_sensor
        - binary_sensor.upstairs_bathroom_window_sensor
        - binary_sensor.ryans_office_rear_window_sensor
        - binary_sensor.ryans_office_side_window_sensor
        - binary_sensor.master_bedroom_front_window_sensor
        - binary_sensor.master_bedroom_side_window_sensor
        - binary_sensor.guest_room_front_window_sensor
        - binary_sensor.guest_room_side_window_sensor
        - binary_sensor.living_room_front_window_sensor
        - binary_sensor.living_room_side_window_1_sensor
        - binary_sensor.living_room_side_window_2_sensor
        - binary_sensor.living_room_rear_window_sensor
        - binary_sensor.half_bath_window_sensor
        - binary_sensor.kitchen_window_sensor
        - binary_sensor.family_room_front_window_1_sensor
        - binary_sensor.family_room_front_window_2_sensor
        - binary_sensor.family_room_side_window_1_sensor
        - binary_sensor.family_room_side_window_2_sensor
        - binary_sensor.family_room_rear_window_1_sensor
        - binary_sensor.family_room_rear_window_2_sensor
        - binary_sensor.family_room_rear_window_3_sensor
        - binary_sensor.laundry_room_window_sensor
        - binary_sensor.movie_room_window_sensor
        - binary_sensor.bedroom_light_button
        - binary_sensor.ryans_bedside_button
        - binary_sensor.kitchen_motion_sensor
        - binary_sensor.laundry_motion_sensor
        - binary_sensor.ryans_office_motion_sensor
        - binary_sensor.media_room_motion_sensor
        - binary_sensor.master_bedroom_motion_sensor
        - binary_sensor.front_outdoor_motion_sensor
        - binary_sensor.basement_door_sensor
        - binary_sensor.front_door_sensor
        - binary_sensor.ryans_office_door_sensor
        - binary_sensor.porch_slider_sensor
        - binary_sensor.family_room_slider
        - binary_sensor.kitchen_water_sensor_moisture
        - binary_sensor.downstairs_bathroom_water_sensor_moisture
        - sensor.lawn_mower_sensor_battery_level
      to: 
        - unavailable
        - unknown
      for:
        minutes: 5
  action:
    - action: notify.ryan_devices
      data:
        title: Sensor Unavailable
        message: "{{trigger.from_state.attributes.friendly_name}} is unavailable, reset"
        data:
          url: /lovelace/devices_view

- alias: ALERT - Notify when the physical mail comes
  id: 48cfaaa2-7814-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: binary_sensor.mailbox_sensor
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.mail_arrived
      state: "off"
  action:
    - action: notify.ryan_devices
      data:
        # UTF-8 issue as of 2022.8
        #title: "\uD83D\uDCEB\uD83D\uDCEB  Mail has arrived  \uD83D\uDCEB\uD83D\uDCEB"
        title: Mail has arrived
        message: ""
    - action: script.amplipi_announce_tts
      data:
        message: "You've got mail"
    - action: homeassistant.turn_on
      entity_id: input_boolean.mail_arrived

- alias: ALERT - Water detected on moisture sensor, notify mobile app
  id: 4db93146-7814-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: binary_sensor.downstairs_bathroom_water_sensor_moisture
      from: "off"
      to: "on"
    - trigger: state
      entity_id: binary_sensor.kitchen_water_sensor_moisture
      from: "off"
      to: "on"
  action:
    - action: script.amplipi_announce_tts
      data:
        message: "Water detected: {{trigger.from_state.attributes.friendly_name}}"
        where: home_alert
    - action: notify.ryan_devices
      data:
        title: "Water detected: {{trigger.from_state.attributes.friendly_name}}"
        message: ""
        data:
          ttl: 0
          priority: high


# 09/16/25 - No reliable sensor on the mower for now, disabling
# - alias: ALERT - Lawn Mower detected away for a long time, notify mobile app
#   id: f4de014a-e2c2-4da6-a79c-2dde29603ac4
#   trigger:
#     - trigger: state
#       entity_id: binary_sensor.lawn_mower
#       from: "off"
#       to: "on"
#       for:
#         hours: 4
#   action:
#     - action: script.amplipi_announce_tts
#       data:
#         message: "Check on Lawn Mower, might be stuck"
#     - action: notify.ryan_devices
#       data:
#         title: "Lawn Mower Stuck"
#         message: "Has been out for 4 hours"
#         data:
#           ttl: 0
#           priority: high

# 09/16/25 - No reliable sensor on the mower for now, disabling
# - alias: ALERT - Lawn Mower has returned
#   id: 26bf48c4-f680-4d64-bcf5-eaa5eae68b5f
#   trigger:
#     - trigger: state
#       entity_id: binary_sensor.lawn_mower
#       from: "on"
#       to: "off"
#   action:
#     - action: notify.ryan_devices
#       data:
#         title: "Lawn Mower Finished"
#         message: ""
#         data:
#           ttl: 0
#           priority: high

- alias: "ALERT - Home Assistant Successfully Started"
  id: 50cedff8-4cd9-4d85-9ea9-dc1726324335
  trigger:
    - trigger: homeassistant
      event: start
  action:
    - action: script.amplipi_announce_tts
      data:
        message: "Home Assistant, online"

########################################
############# Discord Below ############
########################################

# Gif and MP4 not supported via mobile app notification
# Sticking with Discord for now, since we can upload a small video
# watch directly on there
- alias: ALERT - When a motion detection video is created
  id: 54e81d38-7814-11ee-b962-0242ac120002
  trigger:
    - trigger: event
      event_type: folder_watcher
      event_data:
        event_type: created
  action:
    - delay: '00:00:20' # Wait until file is done being modified
    - action: shell_command.convert_camera_recording
    - delay: '00:00:20' # Wait until file is done being modified
    - action: notify.home_assistant # Discord notification name change to Discord server name
      data_template:
        message: 'Motion: {{ trigger.event.data.file }}'
        target: "658174234480082997"
        title: Device Alert
        data:
          images:
            - "/tmp/hass/converted/recording.mp4"
            #- "{{ trigger.event.data.path }}"
    - delay: '00:00:15'
    - action: shell_command.clear_video_directory
