######################################
### ALERT: WHILE AWAY AUTOMATIONS  ###
######################################

- alias: ALERT (AWAY) - Motion at Front Door, notify Mobile App
  id: 604862be-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    trigger: state
    entity_id:
     - input_boolean.someone_at_front_door
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Front Door Motion"
        message: ""
        data:
          ttl: 0
          priority: high
          image: "/api/camera_proxy/camera.outside_doorbell" # Captures image immediately, sends via notification
          url: "/lovelace/camera_view"
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Motion at Rear Patio, notify Mobile App
  id: 65d969a8-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    trigger: state
    entity_id:
      - input_boolean.someone_at_rear_patio
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Rear Patio Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.outside_rear_patio" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Motion at Side Patio, notify Mobile App
  id: 6b54a302-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    trigger: state
    entity_id:
      - input_boolean.someone_at_side_patio
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Side Patio Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.outside_side_patio" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Motion in house
  id: 71fe36c8-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    trigger: state
    entity_id:
     - binary_sensor.living_room_occupancy
     - binary_sensor.thermostat_occupancy
     - binary_sensor.laundry_motion_sensor
     - binary_sensor.kitchen_motion_sensor
     - binary_sensor.ryans_office_motion_sensor
     - binary_sensor.media_room_motion_sensor
     - binary_sensor.master_bedroom_motion_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Motion at home"
        message: "{{trigger.to_state.attributes.friendly_name}} has detected motion"
        data:
          ttl: 0
          priority: high
          url: "/lovelace/camera_view"
          actions:
              - action: "trigger_alarm"
                title: "Trigger Alarm"
    - delay: '00:02:00' # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT (AWAY) - Window Opened in house
  id: 775f8b94-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    trigger: state
    entity_id:
     - binary_sensor.house_windows
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Alert at Home"
        message: "A window at home as been opened"
        data:
          ttl: 0
          priority: high
          url: "/lovelace/camera_view"
          actions:
              - action: "trigger_alarm"
                title: "Trigger Alarm"
    - delay: '00:02:00' # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT (AWAY) - Door Opened into house
  id: 7ed3915e-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    trigger: state
    entity_id:
     - binary_sensor.exterior_doors
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Alert at Home"
        message: "Exterior door has been opened"
        data:
          ttl: 0
          priority: high
          url: "/lovelace/camera_view"
          actions:
              - action: "trigger_alarm"
                title: "Trigger Alarm"
    - delay: '00:02:00' # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT (AWAY) - Basement door has been unlocked
  id: 8a751ece-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: state
      entity_id: lock.basement_door_deadbolt
      attribute: notification
      to: "Manual Unlock"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Basement door unlocked"
        message: ""
        data:
          ttl: 0
          priority: high
          entity_id: camera.outside_under_porch
          url: "/lovelace/camera_view"
          actions:
          - action: PROTECT
            title: Launch Protect App
            url: unifi-protect://

- alias: ALERT (AWAY) - Front door has been unlocked
  id: 90f76b94-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: state
      entity_id: lock.front_door_deadbolt
      attribute: notification
      to: "Manual Unlock"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Front door unlocked"
        message: ""
        data:
          ttl: 0
          priority: high
          image: "/api/camera_proxy/camera.outside_doorbell" # Captures image immediately, sends via notification
          url: "/lovelace/camera_view"

- alias: "ALERT (AWAY) - Alarm Triggered, notify mobile / in house"
  id: 98828ac4-7814-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: alarm_control_panel.alarm
      from: "armed_away"
      to: "pending"
  action:
    #- action: homeassistant.turn_on
    #  entity_id: switch.siren
    - action: notify.ryan_devices
      data:
        title: "Alarm Triggered"
        message: "Notifying emergency services in 60 seconds"
        data:
          ttl: 0
          priority: high
          url: "/"

- alias: "ALERT (AWAY) - Alarm Pending to Triggered, notify NoonLight IFTTT"
  id: 9eaec2fa-7814-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: alarm_control_panel.alarm
      from: "pending"
      to: "triggered"
  action:
    # Trigger IFTTT applet to notify Noonlight
    - action: ifttt.trigger
      data_template:
        event: "alarm_triggered"
    - action: notify.ryan_devices
      data:
        title: "Noonlight Notified"
        message: "Emergency services has been contacted"
        data:
          ttl: 0
          priority: high
          url: "/"