################################
### ALERTS - While Home      ###
################################

- alias: ALERT - Notify when a window was opened
  id: cc8db9b0-7814-11ee-b962-0242ac120002
  mode: single # Only run once at a time
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: state
      entity_id: binary_sensor.house_windows
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: disarmed
  action:
    - action: script.announce_sound
      data:
        name: "window-opened"
    - delay: "00:02:00" # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT - Notify when all windows have been closed
  id: 99a24142-faa5-11ee-a951-0242ac120002
  mode: single # Only run once at a time
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: state
      entity_id: binary_sensor.house_windows
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: disarmed
  action:
    - action: script.announce_sound
      data:
        name: "all-windows-closed"
        override: true
    - delay: "00:02:00" # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT - Notify house when package has been dropped off
  id: 4cd4297d-bb36-42b8-ab99-15188e34e49d
  mode: single # Only run once at a time
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: state
      entity_id: binary_sensor.doorbell_package_detected
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: disarmed
  action:
    - action: script.announce_local
      data:
        message: "Package at front door"
    - delay: "00:02:00" # Prevent multiple runs of this within 2 minute intervals
