######################################
### ALERT: WHILE AWAY AUTOMATIONS  ###
######################################

- alias: ALERT (AWAY) - Motion at Front Door, notify Mobile App
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
     - input_boolean.someone_at_front_door
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Front Door Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.unifi_doorbell" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
          actions:
          - action: "URI"
            title: "Open Unifi"
            uri: 'app://com.ubnt.unifi.protect'
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Motion at Rear Porch, notify Mobile App
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
      - input_boolean.someone_at_rear_porch
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Rear Porch Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.unifi_rear_porch" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Motion in house
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
     - binary_sensor.living_room_occupancy
     - binary_sensor.thermostat_occupancy
     - binary_sensor.laundry_motion_sensor
     - binary_sensor.kitchen_motion_sensor
     - binary_sensor.ryans_office_motion_sensor
     - binary_sensor.media_room_motion_sensor
     - binary_sensor.master_bedroom_motion_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Motion at home"
        message: "{{trigger.to_state.attributes.friendly_name}} has detected motion"
        data:
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
          actions:
              - action: "trigger_alarm"
                title: "Trigger Alarm"
    - delay: '00:02:00' # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT (AWAY) - Window Opened in house
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
     - binary_sensor.house_windows
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Alert at Home"
        message: "A window at home as been opened"
        data:
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
          actions:
              - action: "trigger_alarm"
                title: "Trigger Alarm"
    - delay: '00:02:00' # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT (AWAY) - Door Opened into house
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
     - binary_sensor.exterior_doors
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Alert at Home"
        message: "Exterior door has been opened"
        data:
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
          actions:
              - action: "trigger_alarm"
                title: "Trigger Alarm"
    - delay: '00:02:00' # Prevent multiple runs of this within 2 minute intervals

- alias: ALERT (AWAY) - Garage has opened
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
      - cover.garage_door
    to: 'open'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Garage Door opened at home"
        message: ""
        data:
          image: "/api/camera_proxy/camera.unifi_garage" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"

- alias: ALERT (AWAY) - Basement door has been unlocked
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: lock.basement_door_deadbolt
      attribute: notification
      to: "Manual Unlock"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Basement door unlocked"
        message: ""
        data:
          image: "/api/camera_proxy/camera.unifi_rear_porch" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"

- alias: ALERT (AWAY) - Front door has been unlocked
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - platform: state
      entity_id: lock.front_door_deadbolt
      attribute: notification
      to: "Manual Unlock"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: notify.ryan_devices
      data:
        title: "Front door unlocked"
        message: ""
        data:
          image: "/api/camera_proxy/camera.unifi_front_porch" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"

- alias: "ALERT (AWAY) - Alarm Triggered, notify mobile / in house"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      from: "armed_away"
      to: "pending"
  action:
    #- service: homeassistant.turn_on
    #  entity_id: switch.siren
    - service: notify.ryan_devices
      data:
        title: "Alarm Triggered"
        message: "Notifying emergency services in 60 seconds"
        data:
          ttl: 0
          priority: high
          clickAction: "/"

- alias: "ALERT (AWAY) - Alarm Pending to Triggered, notify NoonLight IFTTT"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      from: "pending"
      to: "triggered"
  action:
    # Trigger IFTTT applet to notify Noonlight
    - service: ifttt.trigger
      data_template:
        event: "alarm_triggered"
    - service: notify.ryan_devices
      data:
        title: "Noonlight Notified"
        message: "Emergency services has been contacted"
        data:
          ttl: 0
          priority: high
          clickAction: "/"