######################################
### ALERT: WHILE AWAY AUTOMATIONS  ###
######################################

- alias: ALERT (AWAY) - Motion at Front Door, notify Mobile App
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
     - binary_sensor.motion_front_door
     - binary_sensor.motion_doorbell
    to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Front Door Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.front_door" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Motion at Rear Porch, notify Mobile App
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
      - binary_sensor.motion_rear_porch
    to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Rear Porch Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.rear_porch" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Motion in house
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
     - binary_sensor.living_room_occupancy
     - binary_sensor.thermostat_occupancy
     - binary_sensor.laundry_motion_sensor
     - binary_sensor.kitchen_motion_sensor
     - binary_sensor.basement_office_motion_sensor_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Motion at home"
        message: "{{trigger.to_state.attributes.friendly_name}} has detected motion"
        data:
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
    - delay: '00:02:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT (AWAY) - Garage has opened
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
      - cover.garage_door
    to: 'open'
  condition:
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Garage Door opened at home"
        message: ""
        data:
          image: "/api/camera_proxy/camera.garage" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"

- alias: ALERT (AWAY) - Door has been unlocked
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
      - lock.media_room_deadbolt
    to: 'unlocked'
  condition:
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Rear door unlocked"
        message: ""
        data:
          image: "/api/camera_proxy/camera.rear_porch" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
          clickAction: "/lovelace/camera_view"
