################################################
### DARK_OUTSIDE CONFIGURATION / AUTOMATION ####
################################################

- alias: GOING DARK - Set dark_outside On (evening, once/day)
  id: d8a964ba-7814-11ee-b962-0242ac120002
  mode: single
  trigger:
    # Daily safety check at 3pm so we always evaluate at least once
    - trigger: time
      at: "15:00:00"

    # Primary: sun below a reasonable "it's dark" threshold
    - trigger: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -4
      for: "00:02:00"

    # Fallback: very dim outside (e.g., storms). Optional—remove if you don't want this.
    - trigger: numeric_state
      entity_id: sensor.front_outdoor_motion_sensor_illuminance
      below: 500
      for: "00:05:00"

  condition:
    # Inclusive: 3:00:00 PM or later
    - condition: template
      value_template: "{{ now() >= today_at('15:00:00') }}"

    # Only if it's currently not marked dark
    - condition: state
      entity_id: input_boolean.dark_outside
      state: "off"

    # Is it dark enough? (guards the 3pm time trigger)
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: -4
        - condition: numeric_state
          entity_id: sensor.front_outdoor_motion_sensor_illuminance
          below: 500

    # Only once per calendar day (use your automation entity_id)
    - condition: template
      value_template: >
        {% set lt = state_attr('automation.going_dark_set_dark_outside_input_boolean_to_on_dark_out', 'last_triggered') %}
        {{ lt is none or lt < today_at('00:00:00') }}

  action:
    - action: homeassistant.turn_on
      target:
        entity_id: input_boolean.dark_outside




# - alias: GOING LIGHT - Set dark_outside input_boolean to Off, bright out
#   id: dedd58d2-7814-11ee-b962-0242ac120002
#   mode: single
#   trigger:
#     - trigger: template
#       value_template: >
#         {{ states('sensor.front_outdoor_motion_sensor_illuminance')|float(0) > 400
#            and 6 <= now().hour < 13 }}
#       for: "00:10:00"
#   condition:
#     - condition: state
#       entity_id: input_boolean.dark_outside
#       state: "on"
#   action:
#     - action: homeassistant.turn_off
#       target:
#         entity_id: input_boolean.dark_outside

- alias: GOING LIGHT - Set dark_outside input_boolean to Off, bright out
  id: dedd58d2-7814-11ee-b962-0242ac120002
  mode: single
  trigger:
    - trigger: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 6         # try 5°, tune to 6–8° if still dim
      for: "00:10:00"
  condition:
    - condition: time
      after: "05:30:00"
      before: "13:00:00"
    - condition: state
      entity_id: input_boolean.dark_outside
      state: "on"
  action:
    - action: homeassistant.turn_off
      target:
        entity_id: input_boolean.dark_outside
