################################################
### DARK_OUTSIDE CONFIGURATION / AUTOMATION ####
################################################

# Darker than 500 Lux Outside 
- alias: GOING DARK - Set dark_outside input_boolean to On, dark out
  id: d8a964ba-7814-11ee-b962-0242ac120002
  trigger:
    # Make sure that the light level is below 500 lx
    - platform: numeric_state
      entity_id: sensor.front_outdoor_motion_sensor_illuminance
      below: 500
  condition:
    # Only execute once per day
    - "{{ state_attr(this.entity_id, 'last_triggered').date() < now().date() }}"
    # Only after 3:00 pm and before 9pm
    # November was hitting 500 lux before 2:30 p.m.
    - condition: time
      after: '15:00:00'
      before: '21:00:00'

    # # Only proceed, if we haven't used the light out in the last 6 hours
    # - condition: template 
    #   value_template: "{{ (state_attr('states.automation.going_dark_set_dark_outside_input_boolean_to_off_light_out.attributes', 'last_triggered') == none) or ((as_timestamp(now())-as_timestamp(states.automation.going_dark_set_dark_outside_input_boolean_to_off_light_out.attributes.last_triggered)) > 21600) }}"
    
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.dark_outside

# Brighter than 400 Lux Outside 
- alias: GOING DARK - Set dark_outside input_boolean to off, light out
  id: dedd58d2-7814-11ee-b962-0242ac120002
  trigger:
    # Make sure that the light level is above 400 lx
    - platform: numeric_state
      entity_id: sensor.front_outdoor_motion_sensor_illuminance
      above: 400
  condition:
    # Only execute once per day
    - "{{ state_attr(this.entity_id, 'last_triggered').date() < now().date() }}"

    # Only proceed, if we haven't used dark off in the last 6 hours
    # - condition: template 
    #   value_template: "{{ (state_attr('states.automation.going_dark_set_dark_outside_input_boolean_to_on_dark_out.attributes', 'last_triggered') == none) or ((as_timestamp(now())-as_timestamp(states.automation.going_dark_set_dark_outside_input_boolean_to_on_dark_out.attributes.last_triggered)) > 21600) }}"
    # # Only after 4 pm and before 9pm
    # - condition: time
    #   after: '05:00:00'
    #   before: '09:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.dark_outside