################################################
### FRONT_DOOR CONFIGURATION / AUTOMATION ####
################################################


# Relying on Outdoor Hue Motion Sensor for main source of motion
# - alias: FRONT DOOR - Whether or not someone is at the front door
#   #max_exceeded: silent # Hide warnings when triggered while in delay
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.front_outdoor_motion_sensor
#       to: 'on'
#   action: 
#     # Go into action directly, since delay can only be done in "Action:" and not "Condition:"
#     # Wait 2 seconds for doorbell to catch on, if neccessary
#     - delay:
#         seconds: 2
#     # Check if doorbell also had motion within the last minute
#     # - condition: template
#     #   value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.motion_camera_doorbell.last_changed)) < 60 }}"
      
#     - condition: template
#       value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.doorbell_person_detected.last_changed)) < 60 }}"
#     # If doorbell did have motion, check that it was in fact a person object
#     # Deprecated object 2/3/23
#     # - condition: state
#     #   entity_id: sensor.doorbell_detected_object
#     #   state: 'person'
#     # Most likely, someone is at the front door turn on input boolean
#     - service: homeassistant.turn_on
#       entity_id: input_boolean.someone_at_front_door
#     # Wait 3 minutes before turning off the boolean
#     - delay:
#         minutes: 3
#     - service: homeassistant.turn_off
#       entity_id: input_boolean.someone_at_front_door


- alias: FRONT DOOR - Whether or not someone is at the front door
  id: f304bee0-7814-11ee-b962-0242ac120002
  #max_exceeded: silent # Hide warnings when triggered while in delay
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_person_detected
      to: 'on'
  action: 
    # Most likely, someone is at the front door turn on input boolean
    - service: homeassistant.turn_on
      entity_id: input_boolean.someone_at_front_door
    # Wait 3 minutes before turning off the boolean
    - delay:
        minutes: 3
    - service: homeassistant.turn_off
      entity_id: input_boolean.someone_at_front_door
