##################################
##### Tesla / Teslamate MQTT #####
##################################

- platform: template
  sensors:
    tesla_est_battery_range_mi:
      friendly_name: Estimated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (float(states('sensor.tesla_est_battery_range_km'), 0.0) / 1.609) | round(2) }}

    tesla_rated_battery_range_mi:
      friendly_name: Rated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (float(states('sensor.tesla_rated_battery_range_km'), 0.0) / 1.609) | round(2) }}

    tesla_ideal_battery_range_mi:
      friendly_name: Ideal Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (float(states('sensor.tesla_ideal_battery_range_km'), 0.0) / 1.609) | round(2) }}

    tesla_odometer_mi:
      friendly_name: Odometer (mi)
      unit_of_measurement: mi
      icon_template: mdi:counter
      value_template: >
        {{ (float(states('sensor.tesla_odometer'), 0.0) / 1.609) | round(2) }}

    tesla_speed_mph:
      friendly_name: Speed (MPH)
      unit_of_measurement: mph
      icon_template: mdi:speedometer
      value_template: >
        {{ (float(states('sensor.tesla_speed'), 0.0) / 1.609) | round(2) }}