###########################
##### SENSOR - Energy #####
###########################

- platform: integration
  name: Server Closet Energy
  source: sensor.server_closet_power
  method: left

- platform: integration
  name: Tesla Energy
  source: sensor.tesla_charger_power_home
  method: left