##################################
##### Tesla / Teslamate MQTT #####
##################################


- platform: template
  sensors:
    tesla_est_battery_range_mi:
      friendly_name: Estimated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (float(states('sensor.tesla_est_battery_range_km'), 0.0) / 1.609) | round(2) }}

    tesla_rated_battery_range_mi:
      friendly_name: Rated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (float(states('sensor.tesla_rated_battery_range_km'), 0.0) / 1.609) | round(2) }}

    tesla_ideal_battery_range_mi:
      friendly_name: Ideal Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (float(states('sensor.tesla_ideal_battery_range_km'), 0.0) / 1.609) | round(2) }}

    tesla_odometer_mi:
      friendly_name: Odometer (mi)
      unit_of_measurement: mi
      icon_template: mdi:counter
      value_template: >
        {{ (float(states('sensor.tesla_odometer'), 0.0) / 1.609) | round(2) }}

    tesla_speed_mph:
      friendly_name: Speed (MPH)
      unit_of_measurement: mph
      icon_template: mdi:speedometer
      value_template: >
        {{ (float(states('sensor.tesla_speed'), 0.0) / 1.609) | round(2) }}

- platform: mqtt
  name: tesla_state
  state_topic: "teslamate/cars/1/state"
  icon: mdi:car-connected

- platform: mqtt
  name: tesla_since
  state_topic: "teslamate/cars/1/since"
  icon: mdi:clock-outline

- platform: mqtt
  name: tesla_healthy
  state_topic: "teslamate/cars/1/healthy"
  icon: mdi:heart-pulse

- platform: mqtt
  name: tesla_version
  state_topic: "teslamate/cars/1/version"
  icon: mdi:alphabetical

- platform: mqtt
  name: tesla_update_available
  state_topic: "teslamate/cars/1/update_available"
  icon: mdi:alarm

- platform: mqtt
  name: tesla_update_version
  state_topic: "teslamate/cars/1/update_version"
  icon: mdi:alphabetical

- platform: mqtt
  name: tesla_geofence
  state_topic: "teslamate/cars/1/geofence"
  icon: mdi:earth

- platform: mqtt
  name: tesla_latitude
  state_topic: "teslamate/cars/1/latitude"
  icon: mdi:crosshairs-gps

- platform: mqtt
  name: tesla_longitude
  state_topic: "teslamate/cars/1/longitude"
  icon: mdi:crosshairs-gps

- platform: mqtt
  name: tesla_locked
  state_topic: "teslamate/cars/1/locked"
  icon: mdi:lock

- platform: mqtt
  name: tesla_sentry_mode
  state_topic: "teslamate/cars/1/sentry_mode"
  icon: mdi:cctv

- platform: mqtt
  name: tesla_windows_open
  state_topic: "teslamate/cars/1/windows_open"
  icon: mdi:car-door

- platform: mqtt
  name: tesla_doors_open
  state_topic: "teslamate/cars/1/doors_open"
  icon: mdi:car-door

- platform: mqtt
  name: tesla_trunk_open
  state_topic: "teslamate/cars/1/trunk_open"
  icon: mdi:car-side

- platform: mqtt
  name: tesla_frunk_open
  state_topic: "teslamate/cars/1/frunk_open"
  icon: mdi:car-side

- platform: mqtt
  name: tesla_is_user_present
  state_topic: "teslamate/cars/1/is_user_present"
  icon: mdi:human-greeting

- platform: mqtt
  name: tesla_is_climate_on
  state_topic: "teslamate/cars/1/is_climate_on"
  icon: mdi:fan

- platform: mqtt
  name: tesla_inside_temp
  state_topic: "teslamate/cars/1/inside_temp"
  unit_of_measurement: °C
  icon: mdi:thermometer-lines

- platform: mqtt
  name: tesla_outside_temp
  state_topic: "teslamate/cars/1/outside_temp"
  unit_of_measurement: °C
  icon: mdi:thermometer-lines

- platform: mqtt
  name: tesla_is_preconditioning
  state_topic: "teslamate/cars/1/is_preconditioning"
  icon: mdi:fan

- platform: mqtt
  name: tesla_odometer
  state_topic: "teslamate/cars/1/odometer"
  unit_of_measurement: km
  icon: mdi:counter

- platform: mqtt
  name: tesla_est_battery_range_km
  state_topic: "teslamate/cars/1/est_battery_range_km"
  unit_of_measurement: "km"
  icon: mdi:gauge

- platform: mqtt
  name: tesla_rated_battery_range_km
  state_topic: "teslamate/cars/1/rated_battery_range_km"
  unit_of_measurement: "km"
  icon: mdi:gauge

- platform: mqtt
  name: tesla_ideal_battery_range_km
  state_topic: "teslamate/cars/1/ideal_battery_range_km"
  unit_of_measurement: "km"
  icon: mdi:gauge

- platform: mqtt
  name: tesla_battery_level
  state_topic: "teslamate/cars/1/battery_level"
  unit_of_measurement: "%"
  icon: mdi:battery-80
  
- platform: mqtt
  name: tesla_usable_battery_level
  state_topic: "teslamate/cars/1/usable_battery_level"
  unit_of_measurement: "%"
  icon: mdi:battery-80

- platform: mqtt
  name: tesla_plugged_in
  state_topic: "teslamate/cars/1/plugged_in"
  icon: mdi:ev-station

- platform: mqtt
  name: tesla_charge_energy_added
  state_topic: "teslamate/cars/1/charge_energy_added"
  unit_of_measurement: "kWh"
  icon: mdi:battery-charging

- platform: mqtt
  name: tesla_charge_limit_soc
  state_topic: "teslamate/cars/1/charge_limit_soc"
  unit_of_measurement: "%"
  icon: mdi:battery-charging-100

- platform: mqtt
  name: tesla_charge_port_door_open
  state_topic: "teslamate/cars/1/charge_port_door_open"
  icon: mdi:ev-plug-tesla

- platform: mqtt
  name: tesla_charger_actual_current
  state_topic: "teslamate/cars/1/charger_actual_current"
  unit_of_measurement: "A"
  icon: mdi:lightning-bolt

- platform: mqtt
  name: tesla_charger_power
  state_topic: "teslamate/cars/1/charger_power"
  icon: mdi:lightning-bolt
  unit_of_measurement: "kW"

- platform: mqtt
  name: tesla_charger_voltage
  state_topic: "teslamate/cars/1/charger_voltage"
  unit_of_measurement: "V"
  icon: mdi:lightning-bolt

- platform: mqtt
  name: tesla_scheduled_charging_start_time
  state_topic: "teslamate/cars/1/scheduled_charging_start_time"
  icon: mdi:clock-outline

- platform: mqtt
  name: tesla_time_to_full_charge
  state_topic: "teslamate/cars/1/time_to_full_charge"
  unit_of_measurement: "h"
  icon: mdi:clock-outline