####################################
####### SENSOR CONFIGURATION  ######
####################################

- platform: rest
  name: Amplipi Presets
  resource: !secret amplipi_get_presets
  method: GET
  headers:
    Accept: "application/json"
  scan_interval: 3600
  value_template: > # Ignore the "Mute All" and "Restore Last Config" from the JSON body
      {% set ns = namespace(filtered_presets=[]) %}
      {% set presets = value_json.presets %}
      {% if presets is not none %}
        {% for preset in presets %}
          {% if preset.name != 'Mute All' and preset.name != 'Restore last config' %}
            {% set ns.filtered_presets = ns.filtered_presets + [preset.name] %}
          {% endif %}
        {% endfor %}
        {{ ns.filtered_presets | join(', ') }}
      {% else %}
        "No presets available"
      {% endif %}
  json_attributes:
    - presets  # Extract the entire presets array, matches within the JSON array
