##################################
##### Critical Device Status #####
##################################

- platform: template
  sensors:
    mac_mini_server:
      value_template: "{% if states.device_tracker.mac_mini_server %}
      {% if is_state('device_tracker.mac_mini_server', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Mac Mini Server'
    synology_nas:
      value_template: "{% if states.device_tracker.synology_nas %}
      {% if is_state('device_tracker.synology_nas', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Synology NAS'
    kitchen_tablet:
      value_template: "{% if states.device_tracker.nexus_9 %}
      {% if is_state('device_tracker.nexus_9', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Kitchen Tablet'
    hdhomerun_extend:
      value_template: "{% if states.device_tracker.hdhomerun_extend %}
      {% if is_state('device_tracker.hdhomerun_extend', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'HDHomeRun Extend'
    logitech_harmony_hub:
      value_template: "{% if states.device_tracker.logitech_harmony_hub %}
      {% if is_state('device_tracker.logitech_harmony_hub', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Logitech Harmony Hub'
    yamaha_reciever:
      value_template: "{% if states.device_tracker.yamaha_rx_v675 %}
      {% if is_state('device_tracker.yamaha_rx_v675', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Yamaha Receiver'
    rear_porch_camera:
      value_template: "{% if states.device_tracker.rear_porch_camera %}
      {% if is_state('device_tracker.rear_porch_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Rear Porch Camera'
      icon_template: mdi:cctv
    side_patio_camera:
      value_template: "{% if states.device_tracker.side_patio_camera %}
      {% if is_state('device_tracker.side_patio_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Front Door Camera'
      icon_template: mdi:cctv
    garage_camera:
      value_template: "{% if states.device_tracker.garage_camera %}
      {% if is_state('device_tracker.garage_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Garage Camera'
      icon_template: mdi:cctv
    doorbell_camera:
      value_template: "{% if states.device_tracker.doorbell %}
      {% if is_state('device_tracker.doorbell', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Doorbell Camera'
      icon_template: mdi:cctv
    living_room_camera:
      value_template: "{% if states.device_tracker.living_room_camera %}
      {% if is_state('device_tracker.living_room_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Living Room Camera'
      icon_template: mdi:cctv