####################################
####### SENSOR CONFIGURATION  ######
####################################

# - platform: filesize
#   file_paths:
#     - /home/homeassistant/.homeassistant/home-assistant.log
#     - /home/homeassistant/.homeassistant/home-assistant_v2.db
#   scan_interval: 1800

- platform: tautulli
  api_key: !secret tautulli_api
  host: !secret tautulli_ip

# Folder for mp4 videos
- platform: folder
  folder: /tmp/hass