##################################
#  Average Temperature for rooms #
##################################


# Define below multiple sensors into one
# only rely on these sensors for automations and views

# -- Movie Room --
- platform: template
  sensors:
    movie_room_avg_temp:
      friendly_name: "Movie Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ '%0.3g'|format(float(states('sensor.movie_room_motion_sensor_temperature'), 65.0)) }}

# -- Laundry Room --
- platform: template
  sensors:
    laundry_room_avg_temp:
      friendly_name: "Laundry Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{'%0.3g'|format((float(states('sensor.laundry_motion_sensor_temperature'), 65.0) 
        + float(states('sensor.basement_door_sensor_temperature'), 65.0)) / 2) }}


# -- Kitchen --
- platform: template
  sensors:
    kitchen_avg_temp:
      friendly_name: "Kitchen Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{'%0.3g'|format((float(states('sensor.kitchen_motion_sensor_temperature'), 65.0) 
        + float(states('sensor.kitchen_window_sensor_temperature'), 65.0)) / 2) }}


#  -- Master Bedroom --
- platform: template
  sensors:
    master_bedroom_avg_temp:
      friendly_name: "Master Bedroom Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{'%0.3g'|format((float(states('sensor.ryans_bedside_button_temperature'), 65.0) 
        + float(states('sensor.bedroom_light_button_temperature'), 65.0)
        + float(states('sensor.master_bedroom_motion_sensor_temperature'), 65.0)) / 3) }}

# -- Guest Room -- only one sensor currently
# - platform: template
#   sensors:
#     guest_room_avg_temp:
#       friendly_name: "Guest Room Temperature"
#       unit_of_measurement: '°F'
#       value_template: >-
#         {{ '%0.3g'|format(float(states('sensor.laundry_motion_sensor_temperature'), 65.0)) }}

# -- Ryan's Office --
- platform: template
  sensors:
    ryans_office_avg_temp:
      friendly_name: "Ryan's Office Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{'%0.3g'|format((float(states('sensor.ryans_office_motion_sensor_temperature'), 65.0) 
        + float(states('sensor.ryans_office_door_sensor_temperature'), 65.0)) / 2) }}

# -- Kelly's Office -- only one sensor currently
# - platform: template
#   sensors:
#     kellys_office_avg_temp:
#       friendly_name: "Guest Room Temperature"
#       unit_of_measurement: '°F'
#       value_template: >-
#         {{ '%0.3g'|format(float(states('sensor.laundry_motion_sensor_temperature'), 65.0)) }}

#  -- Family Room --
- platform: template
  sensors:
    family_room_avg_temp:
      friendly_name: "Family Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{'%0.3g'|format((float(states('sensor.family_room_front_window_1_sensor_temperature'), 65.0) 
        + float(states('sensor.family_room_front_window_2_sensor_temperature'), 65.0)
        + float(states('sensor.family_room_slider_temperature'), 65.0)) / 3) }}

#  -- Living Room --
- platform: template
  sensors:
    living_room_avg_temp:
      friendly_name: "Living Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{'%0.3g'|format((float(states('sensor.front_door_sensor_temperature'), 65.0) 
        + float(states('sensor.living_room_front_window_sensor_temperature'), 65.0)
        + float(states('sensor.living_room_side_window_1_sensor_temperature'), 65.0)) / 3) }}