# 6:00 a.m.
- alias: MORNING - Reset first_movement_ryans_office to off
  id: caff6d18-7815-11ee-b962-0242ac120002
  trigger:
    - trigger: time
      at: '06:00:00'
  action:
    - action: homeassistant.turn_off
      entity_id: input_boolean.first_movement_ryans_office

# 7:00 a.m.
- alias: MORNING - Stop white noise from playing overnight 
  id: 5070fc3e-f906-11ee-a951-0242ac120002
  trigger:
    - trigger: time
      at: '07:00:00'
  action:
    - action: media_player.play_media
      data:
        media_content_id: Stop
        media_content_type: custom
      target:
        entity_id:
        - media_player.guest_room_echo_dot
        - media_player.ryans_office_echo_show
        - media_player.kitchen_echo_show_15
        - media_player.living_room_echo_dot
        - media_player.family_room_echo_dot
        - media_player.movie_room_echo
        - media_player.laundy_room_echo_dot

# 8:00 a.m.
- alias: MORNING - Set all Alexa volume to 60% everyday
  id: cf4face8-7815-11ee-b962-0242ac120002
  trigger:
    - trigger: time
      at: '08:00:00'
  action:
    - action: script.alexa_reset_all_volume

# 8:00 a.m.
- alias: MORNING - Reset mailbox input_boolean to off
  id: d366c2b2-7815-11ee-b962-0242ac120002
  trigger:
    - trigger: time
      at: '08:00:00'
  action:
    - action: homeassistant.turn_off
      entity_id: input_boolean.mail_arrived

# 8:00 a.m.
- alias: MORNING - Reset all lights to default brightness
  id: dbe63fa8-7815-11ee-b962-0242ac120002
  trigger:
    - trigger: time
      at: "08:00:00"
  action:
    - action: light.turn_on
      continue_on_error: true
      target:
        entity_id:
          - light.living_room_floor_lamp
      data:
        brightness_pct: 75
    - action: light.turn_on
      continue_on_error: true
      target:
        entity_id:
          - light.family_room_lights
          - light.living_room_fireplace
          - light.living_room_desk_lamp
          - light.kitchen_lights
          - light.kitchen_ceiling_lights
          - light.ryans_office_desk_lamp
          - light.movie_room_lights
      data:
        brightness_pct: 90
    - action: light.turn_off
      continue_on_error: true
      target:
        entity_id:
          - light.family_room_lights
          - light.living_room_lights
          - light.kitchen_lights
          - light.kitchen_ceiling_lights
          - light.ryans_office_desk_lamp
          - light.movie_room_lights