# 6:00 a.m.
- alias: MORNING - Reset first_movement_basement_office to off
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.first_movement_basement_office

# 8:00 a.m.
- alias: MORNING - Set all Alexa volume to 60% everyday
  trigger:
    - platform: time
      at: '08:00:00'
  action:
    - service: script.alexa_reset_all_volume

# 8:00 a.m.
- alias: MORNING - Reset mailbox input_boolean to off
  trigger:
    - platform: time
      at: '08:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mail_arrived

# 8:00 a.m.
- alias: MORNING - Reset all lights to default brightness
  trigger:
      - platform: time
        at: '08:00:00'
  action:
    - service: light.turn_on
      target:
        entity_id: 
          - light.living_room_lights
          - light.media_room_lights
          - light.kitchen_lights
      data:
        brightness_pct: 100
    - service: light.turn_off
      target:
        entity_id: 
          - light.living_room_lights
          - light.media_room_lights
          - light.kitchen_lights