###################################
##### LIGHTS - GENERAL GROUPS #####
###################################

 ### Master Bedroom ###
- platform: group
  name: Master Bedroom Lights
  unique_id: master_bedroom_lights
  entities:
    - light.bedroom_kellys_bedside
    - light.bedroom_ryans_bedside

 ### Ryan's Office ###
- platform: group
  name: Ryans Office Lights
  unique_id: ryans_office_lights
  entities:
    - light.ryans_office_desk_lamp
    - light.ryans_office_desk_uplighting

 ### Outside ###
- platform: group
  name: Outside Lights
  unique_id: outside_lights
  entities:
    - light.outside_front_door
    - light.outside_side_patio

 ### Kitchen ###
- platform: group
  name: Kitchen Lights
  unique_id: kitchen_lights
  entities:
    - light.kitchen_lamp
    - light.kitchen_dining_area_lamp

 ### Family Room ###
- platform: group
  name: Family Room Lights
  unique_id: family_room_lights
  entities:
    - light.family_room_center_lamp
    - light.family_room_corner_lamp
    - light.family_room_dining_table

 ## Living Room ###
- platform: group
  name: Living Room Lights
  unique_id: living_room_lights
  entities:
    - light.living_room_fireplace
    - light.living_room_desk_lamp
    - light.living_room_floor_lamp

 ### Movie Room ###
# - platform: group
#   name: Movie Room Lights
#   entities:
#     - light.media_room_movie_screen
#     - light.media_room_entry_lamp

 ### Laundry Room ###
# - platform: group
#   name: Laundry Room Lights
#   entities:
#     - light.basement_laundry_light
