###################################
####### LIGHTS - SINGLE USE #######
###################################
# Lights that needed to be converted to one entity

- platform: group
  name: Kitchen Pendants
  unique_id: kitchen_pendants
  entities:
    - light.kitchen_pendant_left
    - light.kitchen_pendant_right
 
- platform: group
  name: Living Room Fireplace
  unique_id: living_room_fireplace
  entities:
    - light.living_room_fireplace_left
    - light.living_room_fireplace_right

- platform: group
  name: Front Door
  unique_id: outside_front_door
  entities:
    - light.outside_front_door_left
    - light.outside_front_door_right

- platform: group
  name: Dining Table
  unique_id: family_room_dining_table
  entities:
    - light.dining_table_light_left_light
    - light.dining_table_light_middle_light
    - light.dining_table_light_right_light