###################################
##### LIGHTS - GENERAL GROUPS #####
###################################

 ### Master Bedroom ###
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.bedroom_kellys_bedside
    - light.bedroom_ryans_bedside

 ### Ryan's Office ###
- platform: group
  name: Ryans Office Lights
  entities:
    - light.ryans_office_desk_lamp

 ### Outside ###
- platform: group
  name: Outside Lights
  entities:
    - light.outside_front_door
    - light.outside_side_patio

 ### Kitchen ###
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_lamp
    - light.kitchen_dining_area_lamp

 ### Family Room ###
- platform: group
  name: Family Room Lights
  entities:
    - light.family_room_center_lamp
    - light.family_room_corner_lamp

 ## Living Room ###
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_fireplace
    - light.living_room_lamp

 ### Movie Room ###
# - platform: group
#   name: Movie Room Lights
#   entities:
#     - light.media_room_movie_screen
#     - light.media_room_entry_lamp

 ### Laundry Room ###
# - platform: group
#   name: Laundry Room Lights
#   entities:
#     - light.basement_laundry_light
