#########################
### ALARM AUTOMATIONS ###
#########################

- alias: "ALARM - Disable Alarm from Schlage Deadbolt"
  id: f2bdcc78-7815-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: lock.basement_door_deadbolt
      attribute: notification
      to: "Keypad Unlock"
    - trigger: state
      entity_id: lock.basement_door_deadbolt
      attribute: notification
      to: "RF Unlock"
    - trigger: state
      entity_id: lock.front_door_deadbolt
      attribute: notification
      to: "Keypad Unlock"
    - trigger: state
      entity_id: lock.front_door_deadbolt
      attribute: notification
      to: "RF Unlock"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - action: alarm_control_panel.alarm_disarm
      target:
        entity_id: alarm_control_panel.alarm

- alias: ALARM - Send Notification when home is disarmed
  id: fd9a8cb2-7815-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: alarm_control_panel.alarm
      to: disarmed
  action:
    - action: notify.ryan_devices
      data:
        title: "Home set to: Disarmed"
        message: ""
        
- alias: ALARM - Send Notification when home is armed
  id: f939fd06-7815-11ee-b962-0242ac120002
  trigger:
    - trigger: state
      entity_id: alarm_control_panel.alarm
      to: armed_away
  action:
    - action: notify.ryan_devices
      data:
        title: "Home set to: Armed Away"
        message: ""