#########################
### ALARM AUTOMATIONS ###
#########################

- alias: "ALARM - Disable Alarm from Schlage Deadbolt"
  trigger:
    - platform: state
      entity_id: lock.media_room_deadbolt
      attribute: notification
      to: "Keypad Unlock"
    - platform: state
      entity_id: lock.media_room_deadbolt
      attribute: notification
      to: "RF Unlock"
    - platform: state
      entity_id: lock.front_door_deadbolt
      attribute: notification
      to: "Keypad Unlock"
    - platform: state
      entity_id: lock.front_door_deadbolt
      attribute: notification
      to: "RF Unlock"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_disarm
      target:
        entity_id: alarm_control_panel.alarm
    #  Alexa Guard currently sends a notification already
    #- service: notify.mobile_app_pixel_3
    #  data:
    #    title: "Alarm Disarmed"
    #    message: ""
    #    data:
    #      ttl: 0
    #      priority: high
    #      clickAction: "/"

- alias: "ALARM - Set Alexa Guard to on when alarm goes on"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: armed_away
  action:
    - service: alarm_control_panel.alarm_arm_away
      target:
        entity_id: alarm_control_panel.alexa_guard_de7c8

- alias: "ALARM - Set Alexa Guard to off when alarm goes off"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: disarmed
  action:
    - service: alarm_control_panel.alarm_disarm
      target:
        entity_id: alarm_control_panel.alexa_guard_de7c8