####################################
### ALERT / DISCORD AUTOMATIONS  ###
####################################



########################################
######### Companion App Below ##########
########################################

- alias: ALERT - Motion at Front Door, notify Mobile App
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
     - binary_sensor.motion_front_door
     - binary_sensor.motion_doorbell
    to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Front Door Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.front_door" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals

- alias: ALERT - Motion at Rear Porch, notify Mobile App
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
      - binary_sensor.motion_rear_porch
    to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status
      state: 'Away'
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Rear Porch Motion"
        message: ""
        data:
          image: "/api/camera_proxy/camera.rear_porch" #Captures image immediately, sends via notification
          ttl: 0
          priority: high
    - delay: '00:05:00' # Prevent multiple runs of this within 5 minute intervals


- alias: ALERT - Doorbell rang, notify Mobile App
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_doorbell #Press of the doorbell
    from: 'off'
    to: 'on'
  action:
    - delay: '00:00:02' # Wait 2 seconds so we don't get their finger in the camera
    - service: notify.mobile_app_pixel_3
      data:
        title: "Doorbell Rang"
        message: ""
        data:
          image: "/api/camera_proxy/camera.doorbell" #Captures image immediately, sends via notification
          ttl: 0
          priority: high

- alias: ALERT - When a critical device goes offline to mobile app
  trigger:
    - platform: state
      entity_id: 
        - sensor.mac_mini_server
        - sensor.hdhomerun_extend
        - sensor.hue_bridge
        - sensor.kitchen_tablet
        - sensor.logitech_harmony_hub
        - sensor.smartthings_hub
        - sensor.synology_nas
        - sensor.yamaha_reciever
        - sensor.front_door_camera
        - sensor.doorbell_camera
        - sensor.living_room_camera
        - sensor.garage_camera
      from: 'Online'
      to: 'Offline'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {% if states.automation.alert_when_a_critical_device_goes_offline.last_triggered is not none %}
            {% if as_timestamp(now()) | int - as_timestamp(states.automation.alert_when_a_critical_device_goes_offline.attributes.last_triggered) | int > 3600 %} 
              true
            {% else %} 
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
  action:
    service: notify.mobile_app_pixel_3
    data:
      title: "Critical Device Alert"
      message: "{{trigger.to_state.attributes.friendly_name}} has gone offline."
      data:
        ttl: 0
        priority: high


- alias: ALERT - HA Persistent Notifications to Mobile App
  trigger:
  - event_data:
      domain: persistent_notification
      service: create
    event_type: call_service
    platform: event
  condition: []
  action:
    service: notify.mobile_app_pixel_3
    data:
      title: "{{trigger.event.data.service_data.title}}"
      message: "{{trigger.event.data.service_data.message}}"

- alias: ALERT - HA Update Available to Mobile App
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    service: notify.mobile_app_pixel_3
    data:
      title: "New Version of HASS Available"
      message: "Release Notes for {{ state_attr('binary_sensor.updater', 'newest_version') }}: {{ state_attr('binary_sensor.updater', 'release_notes') }}"   
      data:
        ttl: 0
        priority: high
        clickAction: "{{ state_attr('binary_sensor.updater', 'release_notes') }}"

- alias: ALERT - Low battery on sensor, notify Mobile App
  mode: single # Only run once at a time  
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.bedroom_light_button_battery_level
      - sensor.kitchen_motion_sensor_battery_level
      - sensor.laundry_motion_sensor_battery_level
      - sensor.ryans_bedside_button_battery_level
      - sensor.schlage_allegion_be469_touchscreen_deadbolt_battery_level
      - sensor.basement_office_motion_sensor_battery_level
    below: 30
  action:
    - service: notify.mobile_app_pixel_3
      data:
        title: "Sensor Battery Low"
        message: "{{trigger.from_state.attributes.friendly_name}} is low"


########################################
############# Discord Below ############
########################################

# Gif and MP4 not supported via mobile app notification
# Sticking with Discord for now, since we can upload a small video
# watch directly on there
- alias: ALERT - When a motion detection video is created
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
  action:
    - delay: '00:00:20' #Wait until file is done being modified
    - service: shell_command.convert_camera_recording
    - delay: '00:00:20' #Wait until file is done being modified
    - service: notify.discord
      data_template:
        message: 'Motion detected'
        target: "658174234480082997"
        title: Device Alert
        data:
          images:
            - "/tmp/hass/converted/recording.mp4"
            #- "{{ trigger.event.data.path }}"
    - delay: '00:00:15'
    - service: shell_command.clear_video_directory