############################
### CAMERA AUTOMATIONS   ###
############################

- alias: CAMERAS - Capture on front door motion
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.front_door_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family 
      state: 'not_home'
  action:
    - service: script.capture_front_door_video

- alias: CAMERAS - Capture on rear porch motion
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.rear_porch_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family 
      state: 'not_home'
  action:
    - service: script.capture_rear_porch_video

- alias: CAMERAS - Notify Alexa of Front Door only if Ryan is home
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.front_door_motion_sensor
      to: 'on'
  condition:
    # If Ryan is home
    - condition: template
      value_template: "{{ is_state('sensor.ryan_status', 'Home') }}"
    # If last triggered is null, or it hasn't been triggered in the last five minutes
    - condition: template
      value_template: >-
        "{{ state_attr('states.automation.notify_alexa_of_front_door_only_if_ryan_is_home.attributes', 'last_triggered') == none or
         (as_timestamp(now())-as_timestamp(states.automation.notify_alexa_of_front_door_only_if_ryan_is_home.attributes.last_triggered)) > 300 }}"
    # If the front porch light hasn't been turned off/on in the last 15 seconds
    # was causing a notification when you turned the light on/off
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.front_porch.last_triggered)) > 15 }}"
  action:
    - service: script.alexa_notify_main_floor
      data:
        title: "Motion detected"
        message: "Front Door"
    - service: script.alexa_notify_basement_office
      data:
        title: "Motion detected"
        message: "Front Door"
