############################
### CAMERA AUTOMATIONS   ###
############################


# Set mode to queued so that there isn't conflicting runs when called while another is running
- alias: CAMERAS - Capture on front door motion
  mode: queued
  trigger:
    platform: state
    entity_id:
     - binary_sensor.motion_front_door
     - binary_sensor.motion_doorbell
    to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status 
      state: 'Away'
  action:
    - service: script.capture_front_door_video

# Set mode to queued so that there isn't conflicting runs when called while another is running
- alias: CAMERAS - Capture on rear porch motion
  mode: queued
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.motion_rear_porch
      to: 'on'
  condition:
    - condition: state
      entity_id: variable.family_status 
      state: 'Away'
  action:
    - service: script.capture_rear_porch_video

- alias: CAMERAS - Notify Alexa of Front Door only if Ryan is home
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.motion_front_door
      to: 'on'
  condition:
    # If Ryan is home
    - condition: template
      value_template: "{{ is_state('variable.ryan_status', 'Home') }}"
    # If last triggered is null, or it hasn't been triggered in the last five minutes
    - condition: template
      value_template: "{{ state_attr('states.automation.notify_alexa_of_front_door_only_if_ryan_is_home.attributes', 'last_triggered') == none or (as_timestamp(now())-as_timestamp(states.automation.notify_alexa_of_front_door_only_if_ryan_is_home.attributes.last_triggered)) > 300 }}"
    # If the front porch light hasn't been turned off/on in the last 15 seconds
    # was causing a notification when you turned the light on/off
    # "last_changed", must be used for light entity not "last_triggered" like automations
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.outside_front_porch.last_changed)) > 15 }}"
  action:
    - service: script.alexa_notify_house
      data:
        message: "Front Door"
