###################################
### DEVICE TRACKING AUTOMATIONS ###
###################################

- alias: DEVICE_TRACK - Nobody home, lock doors, arm alexa, set Tstat to Away, turn off Lights, etc..
  trigger:
    - platform: state
      entity_id: sensor.family_status
      from: 'Home'
      to: 'Away'
  action:
    - service: lock.lock                                # Lock Media Room Deadbolt
      entity_id: lock.basement_door_deadbolt
    - service: lock.lock                                # Lock Front Door Deadbolt
      entity_id: lock.front_door_deadbolt
    - service: alarm_control_panel.alarm_arm_away       # Arm Alexa for guard mode
      entity_id: alarm_control_panel.alarm
    # - service: climate.set_preset_mode                  # Set thermostat for Away mode
    #   data:
    #     entity_id: climate.thermostat, climate.media_room
    #     preset_mode: 'Away'
    - service: light.turn_off                           # Turn off all lights in home
      entity_id: all
    # Only proceed if its dark outside with the following services
    - condition: state
      entity_id: input_boolean.dark_outside
      state: 'on'
    # Keep lights that should be on while away, on
    - service: light.turn_on
      entity_id: light.sun_based_lights_away


- alias: DEVICE_TRACK - Someone arrived home, disable alarm, set Thermostat to Home
  trigger:
    - platform: state
      entity_id: sensor.family_status
      from: 'Away'
      to: 'Home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      # Only change thermostat when arriving home, if we aren't in "Sleep" mode on Ecobee
      # will probably be during the night if this is true
    # - condition: template
    #   value_template: '{{ states.climate.thermostat.attributes.preset_mode != "Sleep" }}'
    # - service: climate.set_preset_mode
    #   data:
    #     entity_id: climate.thermostat, climate.media_room
    #     preset_mode: 'Home'
