###################################
### DEVICE TRACKING AUTOMATIONS ###
###################################

- alias: DEVICE_TRACK - Nobody home, lock doors, arm alexa, set Tstat to Away, turn off Lights, etc..
  trigger:
    - platform: state
      entity_id: variable.family_status
      from: 'Home'
      to: 'Away'
  action:
    - service: lock.lock
      entity_id: lock.media_room_deadbolt
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alexa_guard_de7c8
    - service: climate.set_preset_mode
      data:
        entity_id: climate.thermostat, climate.media_room
        preset_mode: 'Away'
    - service: light.turn_off
      entity_id: all
    # Only proceed if its dark outside with the following services
    - condition: or 
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:45:00"
        - condition: sun
          before: sunrise
          before_offset: "+00:45:00"
    # Keep lights that should be on while away, on
    - service: light.turn_on
      entity_id: light.sun_based_lights_away


- alias: DEVICE_TRACK - Someone arrived home, disable alexa guard, set Thermostat to Home
  trigger:
    - platform: state
      entity_id: variable.family_status
      from: 'Away'
      to: 'Home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alexa_guard_de7c8
      # Only change thermostat when arriving home, if we aren't in "Sleep" mode on Ecobee
      # will probably be during the night if this is true
    - condition: template
      value_template: '{{ states.climate.thermostat.attributes.preset_mode != "Sleep" }}'
    - service: climate.set_preset_mode
      data:
        entity_id: climate.thermostat, climate.media_room
        preset_mode: 'Home'
