############################
### LIGHTING AUTOMATIONS ###
############################

- alias: LIGHTS - Turn on Front Porch Light, if motion detected
  id: 1fd1b260-7816-11ee-b962-0242ac120002
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    - trigger: state
      entity_id: input_boolean.someone_at_front_door
      to: "on"
  condition:
    - condition: state
      entity_id: light.outside_front_door
      state: "off"
    - condition: state
      entity_id: input_boolean.dark_outside
      state: "on"
  action:
    - action: light.turn_on
      continue_on_error: true
      entity_id: light.outside_front_door
    # If it's after 9:00 pm, or before 5:00 am turn off the light
    - condition: time
      after: "21:00:00"
      before: "05:00:00"
    - delay: "00:03:00"
    - action: light.turn_off
      continue_on_error: true
      entity_id: light.outside_front_door