############################
### LIGHTING AUTOMATIONS ###
############################


# Turn on Living room lights to 90%, Outside to 100%
# turn off unneeded lights if nobodoy is home
- alias: LIGHTS - Turn on lights 1:30hr before sun sets
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:30:00"
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.living_room_lights
        brightness_pct: 90
        transition: 10
    - service: light.turn_on
      data:
        entity_id: 
          - light.outside_lights
        brightness_pct: 100
        transition: 2
      # Only proceed if someone is not home
      # turn off lights that we don't want to leave on
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - service: light.turn_off
      entity_id: 
        - light.center_lamp
        - light.bookcase_lamp

- alias: LIGHTS - Turn off outside lights at 11:30pm
  trigger:
    - platform: time
      at: '23:30:00'
  action:
      service: light.turn_off
      entity_id: light.outside_lights

- alias: LIGHTS - Outside lights off 9:00pm, both home during week
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family 
        state: 'home'
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
      service: light.turn_off
      entity_id: light.outside_lights



# Turn off Unifi AP's LEDs at night
- alias: LIGHTS - Turn off Unifi AP LED at 11:00pm
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: shell_command.unifi_ap_light_off

# Turn on Unifi AP's LEDs in morning
- alias: LIGHTS - Turn on Unifi AP LED in the morning
  trigger:
    - platform: sun
      event: sunrise
      offset: "+0:30:00"
  action:
    - service: shell_command.unifi_ap_light_on


- alias: LIGHTS - Turn on Front Porch Light, if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: light.front_porch
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: '5:00:00'
  action:
    - service: light.turn_on
      entity_id: light.front_porch
    - delay: '00:03:00'
    - service: light.turn_off
      entity_id: light.front_porch

- alias: LIGHTS - Turn on Rear Porch Light, if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.rear_porch_motion_sensor
      to: 'on'
  condition:
    # Only trigger if the back porch light hasn't been turned off/on it hasn't been turned off in the last 30 seconds
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.back_porch.last_changed)) > 30 }}"
    - condition: state
      entity_id: light.back_porch
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: '5:00:00'
  action:
    - service: light.turn_on
      entity_id: 
        - light.back_porch
        - light.porch_flood
        - light.driveway_flood
    - delay: '00:03:00'
    - service: light.turn_off
      entity_id: 
        - light.back_porch
        - light.porch_flood
        - light.driveway_flood
