############################
### LIGHTING AUTOMATIONS ###
############################

- alias: LIGHTS - Turn on Front Porch Light, if motion detected
  max_exceeded: silent # Hide warnings when triggered while in delay.
  trigger:
    platform: state
    entity_id:
    - binary_sensor.motion_front_door
    - binary_sensor.motion_doorbell
    to: 'on'
  condition:
    - condition: state
      entity_id: light.outside_front_porch
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: '5:00:00'
  action:
    - service: light.turn_on
      entity_id: light.outside_front_porch
    - delay: '00:03:00'
    - service: light.turn_off
      entity_id: light.outside_front_porch

- alias: LIGHTS - Turn on Porch/Floods, if motion detected (Late night)
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_rear_porch
      to: 'on'
  mode: restart
  condition:
    # Only trigger if the back porch light hasn't been turned off/on it hasn't been turned off in the last 30 seconds
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.outside_back_porch.last_changed)) > 30 }}"
    - condition: state
      entity_id: light.outside_back_porch
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: '5:00:00'
  action:
    - service: light.turn_on
      entity_id: 
        - light.outside_back_porch
        - light.outside_porch_flood
        - light.outside_driveway_flood
    - delay: '00:03:00'
    - service: light.turn_off
      entity_id: 
        - light.outside_back_porch
        - light.outside_porch_flood
        - light.outside_driveway_flood

- alias: LIGHTS - Turn on Floods, if motion detected (While dark/porch on)
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_rear_porch
      to: 'on'
  mode: restart
  condition:
    # Only trigger if the back porch light hasn't been turned off/on it hasn't been turned off in the last 30 seconds
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.outside_back_porch.last_changed)) > 30 }}"
    - condition: state
      entity_id: light.outside_back_porch
      state: 'on'
    # Trigger outside of the "Late night" time window"
    - condition: time
      after: '15:00:00'
      before: '21:00:00'
  action:
    - service: light.turn_on
      entity_id: 
        - light.outside_porch_flood
        - light.outside_driveway_flood
    - delay: '00:03:00'
    - service: light.turn_off
      entity_id: 
        - light.outside_porch_flood
        - light.outside_driveway_flood
