############################
### LIGHTING AUTOMATIONS ###
############################

- alias: LIGHTS - Turn on Front Porch Light, if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: light.front_porch
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: '5:00:00'
  action:
    - service: light.turn_on
      entity_id: light.front_porch
    - delay: '00:03:00'
    - service: light.turn_off
      entity_id: light.front_porch

- alias: LIGHTS - Turn on Rear Porch Light, if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.rear_porch_motion_sensor
      to: 'on'
  condition:
    # Only trigger if the back porch light hasn't been turned off/on it hasn't been turned off in the last 30 seconds
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.back_porch.last_changed)) > 30 }}"
    - condition: state
      entity_id: light.back_porch
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: '5:00:00'
  action:
    - service: light.turn_on
      entity_id: 
        - light.back_porch
        - light.porch_flood
        - light.driveway_flood
    - delay: '00:03:00'
    - service: light.turn_off
      entity_id: 
        - light.back_porch
        - light.porch_flood
        - light.driveway_flood
