###################################
### MOBILE RESPONSE AUTOMATIONS ###
###################################

- alias: MOBILE RESPONSE - Close Garage Door
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: close_garage_door
  action:
    service: script.close_garage_door