############################
###   MQTT AUTOMATIONS   ###
############################

- alias: MQTT - Announce movie has been added to Plex on Alexa
  trigger:
    - platform: mqtt
      topic: homeassistant/tautilli
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: variable.family_status
        state: 'Home'
      - condition: time
        after: '07:00:00'
        before: '23:30:00'
  action:
    - service: script.alexa_notify_house
      data_template: # !!! MUST BE DEFINED AS DATA_TEMPLATE FOR USING TRIGGER PAYLOAD
        title: "New Movie Added"
        message: "{{ trigger.payload_json['body'] }} was recently added to Plex."

- alias: MQTT - Save movie has been added to Plex on Alexa for later
  trigger:
    - platform: mqtt
      topic: homeassistant/tautilli
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: variable.family_status
        state: 'Away'
      - condition: time
        before: '07:00:00'
        after: '23:30:00'
  action:
    - service: variable.set_variable
      data_template:
        variable: tautilli_data
        value: "{{ trigger.payload_json['body'] }}, {{ states.variable.tautilli_data.state }}"
