####################################
### BINARY SENSOR CONFIGURATION  ###
####################################

# Binary sensor for device critical, if one of them goes offline
- platform: template
  sensors:
    device_critical:
      value_template: >-
        "{{ is_state('states.sensor.garage_camera','Offline')
        or is_state('states.sensor.side_patio_camera', 'Offline')
        or is_state('states.sensor.doorbell_camera', 'Offline')
        or is_state('states.sensor.rear_porch_camera', 'Offline')
        or is_state('states.sensor.living_room_camera', 'Offline')
        or is_state('states.sensor.hdhomerun_extend', 'Offline')
        or is_state('states.sensor.kitchen_tablet', 'Offline')
        or is_state('states.sensor.logitech_harmony_hub', 'Offline')
        or is_state('states.sensor.synology_nas', 'Offline')
        or is_state('states.sensor.mac_mini_server', 'Offline')
        or is_state('states.sensor.yamaha_receiver', 'Offline') }}"
      friendly_name: 'Device Critical'
