####################################
####### COVER CONFIGURATION  ######
####################################

# Convert garage door to "cover" to get proper signaling / toggles
# soltion for all-in-one with a sensor / switch combo
- platform: template
  covers:
    garage_door:
      unique_id: cover.garage_door # Allows UI changes
      device_class: garage
      friendly_name: "Garage Door"
      value_template: "{{ states('binary_sensor.garage_door') == 'on' }}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_door_toggle
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_door_toggle
      icon_template: >-
        {% if is_state('binary_sensor.garage_door', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}