####################################
####### LIGHTS CONFIGURATION  ######
####################################

## Wemo Lights -> Regular lights
#- platform: switch
#  name: Bookshelf Lamp
#  entity_id: switch.bookshelf_lamp


 ### Media Room ###
- platform: group
  name: Media Room Lights
  entities:
    - light.media_room_movie_screen
    - light.media_room_entry_lamp


### Basement Office ###
- platform: group
  name: Basement Office Lights
  entities:
    - light.basement_ryans_desk_lamp
    - light.basement_office_recessed
    - light.ryans_desk_uplighting


 ### Laundry Room ###
- platform: group
  name: Laundry Room Lights
  entities:
    - light.basement_laundry_light


 ### Living Room ###
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_center_lamp
    - light.living_room_entry_lamp
    - light.living_room_bookcase_lamp


 ### Master Bedroom ###
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.bedroom_dresser_lamp
    - light.bedroom_kellys_bedside
    - light.bedroom_ryans_bedside


 ### Outside ###
- platform: group
  name: Outside Lights
  entities:
    - light.outside_back_porch
    - light.outside_front_porch
    - light.outside_driveway_flood
    - light.outside_porch_flood


 ### Kitchen ###
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_undercabinet_lights
    - light.kitchen_nook


### Sun Based Lights - While we're Home ###
- platform: group
  name: Sun Based Lights Home
  entities:
    - light.outside_back_porch
    - light.outside_front_porch
    - light.living_room_lights

### Sun Based Lights - While we're away ###
- platform: group
  name: Sun Based Lights Away
  entities:
    - light.outside_back_porch
    - light.outside_front_porch
    - light.living_room_entry_lamp


#### SINGLE USE ENTITIES, NOT NAMED "LIGHTS" ####
- platform: group
  name: Kitchen Nook
  entities:
    - light.kitchen_nook_left
    - light.kitchen_nook_right

- platform: group
  name: Kitchen Overhead
  entities:
    - light.kitchen_overhead_one
    - light.kitchen_overhead_two
 
- platform: group
  name: Media Room Movie Screen
  entities:
    - light.media_room_movie_left
    - light.media_room_movie_right
