  ## Leviton Z-Wave Dimmer Switch -- Kitchen
- platform: mqtt
  name: Undercabinet Lights
  state_topic: "smartthings/Undercabinet Lights/switch"
  command_topic: "smartthings/Undercabinet Lights/switch"
  brightness_state_topic: "smartthings/Undercabinet Lights/level"
  brightness_command_topic: "smartthings/Undercabinet Lights/level"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  optimistic: true
  retain: true

## Leviton Z-Wave Dimmer Switch -- Dining Room Table
- platform: mqtt
  name: Dining Room Table
  state_topic: "smartthings/Dining Room Table/switch"
  command_topic: "smartthings/Dining Room Table/switch"
  brightness_state_topic: "smartthings/Dining Room Table/level"
  brightness_command_topic: "smartthings/Dining Room Table/level"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  optimistic: true
  retain: true

## Leviton Z-Wave Dimmer Switch -- Basement Office
- platform: mqtt
  name: Basement Office
  state_topic: "smartthings/Basement Office Dimmer/switch"
  command_topic: "smartthings/Basement Office Dimmer/switch"
  brightness_state_topic: "smartthings/Basement Office Dimmer/level"
  brightness_command_topic: "smartthings/Basement Office Dimmer/level"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  optimistic: true
  retain: true


 ## Wemo Lights -> Regular lights
#- platform: switch
#  name: Bookshelf Lamp
#  entity_id: switch.bookshelf_lamp



 ### Media Room ###
- platform: group
  name: Media Room Lights
  entities:
    - light.movie_screen
    - light.rear_entry_lamp

### Basement Office ###
- platform: group
  name: Basement Office Lights
  entities:
    - light.ryans_office_lamp
    - light.basement_office_recessed


 ### Laundry Room ###
- platform: group
  name: Laundry Room Lights
  entities:
    - light.laundry_light


 ### Living Room ###
- platform: group
  name: Living Room Lights
  entities:
    - light.center_lamp
    - light.entry_lamp
    - light.bookcase_lamp


 ### Master Bedroom ###
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.dresser_lamp
    - light.kellys_bedside
    - light.ryans_bedside


 ### Outside ###
- platform: group
  name: Outside Lights
  entities:
    - light.back_porch
    - light.front_porch
    - light.driveway_flood
    - light.porch_flood


 ### Kitchen ###
- platform: group
  name: Kitchen Lights
  entities:
    - light.undercabinet_lights
    - light.kitchen_nook


### Sun Based Lights - While we're Home ###
- platform: group
  name: Sun Based Lights Home
  entities:
    - light.back_porch
    - light.front_porch
    - light.living_room_lights

### Sun Based Lights - While we're away ###
- platform: group
  name: Sun Based Lights Away
  entities:
    - light.back_porch
    - light.front_porch
    - light.entry_lamp


#### SINGLE USE ENTITIES, NOT NAMED "LIGHTS" ###
- platform: group
  name: Kitchen Nook
  entities:
    - light.nook_left
    - light.nook_right

- platform: group
  name: Overhead Kitchen
  entities:
    - light.kitchen_overhead_one
    - light.kitchen_overhead_two
 
- platform: group
  name: Movie Screen
  entities:
    - light.movie_left
    - light.movie_right
