####################################
####### SENSOR CONFIGURATION  ######
####################################

- platform: filesize
  file_paths:
    - /home/homeassistant/.homeassistant/home-assistant.log
    - /home/homeassistant/.homeassistant/home-assistant_v2.db
  scan_interval: 1800

- platform: radarr
  api_key: !secret radarr_api
  host: !secret radarr_ip
  port: !secret radarr_port
  days: 7

- platform: tautulli
  api_key: !secret tautulli_api
  host: !secret tautulli_ip

- platform: template
  sensors:
    ryan_status:
      value_template: '{{ states.variable.ryan_status.state }}'
      friendly_name: 'Ryan'
    kelly_status:
      value_template: '{{ states.variable.kelly_status.state }}'
      friendly_name: 'Kelly'

# 2/26/21 not in use
- platform: template
  sensors:
    dryer_status:
      unique_id: sensor.dryer_status # Allow UI customizations
      value_template: "{{ states('input_select.dryer_status') }}"
      icon_template: >-
        {% if is_state('input_select.dryer_status', 'Idle') %}
          mdi:tumble-dryer-off
        {% else %}
          mdi:tumble-dryer
        {% endif %}

- platform: template
  sensors:
    washer_remaining_time:
      unique_id: sensor.washer_remaining_time # Allow UI customizations
      value_template: >-
        {% if is_state_attr('sensor.washing_machine', 'remain_time', '0:00') %}
          Off
        {% else %}
          {{ state_attr('sensor.washing_machine', 'remain_time') }}
        {% endif %}
      icon_template: >-
        {% if is_state_attr('sensor.washing_machine', 'remain_time', '0:00') %}
          mdi:tumble-washer-off
        {% else %}
          mdi:tumble-washer
        {% endif %}

# Climate.thermostat doesn't demonstration changes to the preset_mode in the logbook or history
- platform: template
  sensors:
    ecobee_preset:
      value_template: '{{ states.climate.thermostat.attributes.preset_mode }}'
      friendly_name: "Ecobee Preset"

# Harmony Remote sensor for current activity
- platform: template
  sensors:
      harmony_hub_activity:
        value_template: '{{ state_attr("remote.harmony_hub", "current_activity") }}'
        friendly_name: 'Media Room'

# Folder for mp4 videos
- platform: folder
  folder: /tmp/hass


####################################
#  Motion sensors on input_boolean #
####################################

#- platform: template
#  sensors:
#    motion_front_door:
#      friendly_name: Front Door Motion
#      value_template: "{{ states.input_boolean.office_occupancy.state == 'on' }}"
#      entity_id: binary_sensor.motion_front_door
#      device_class: motion


##################################
#  Average Temperature for rooms #
##################################
# Define below multiple sensors into one
# only rely on these sensors for automations and views

#  -- Bedroom --
- platform: template
  sensors:
    bedroom_avg_temp:
      friendly_name: "Bedroom Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ '%0.3g'|format((states('sensor.ryans_bedside_button_temperature')|float + states('sensor.bedroom_light_button_temperature')|float + states('sensor.master_bedroom_motion_sensor_temperature')|float)  / 3 | round(2)) }}


#  -- Living Room --
- platform: template
  sensors:
    living_room_avg_temp:
      friendly_name: "Living Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ '%0.3g'|format((states('sensor.living_room_temperature')|float + states('sensor.thermostat_temperature')|float)  / 2 | round(2)) }}

# -- Media Room -- only one sensor currently
- platform: template
  sensors:
    media_room_avg_temp:
      friendly_name: "Media Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ (states('sensor.media_room_temperature')|float | round(2)) }}
        
# -- Kitchen -- only one sensor currently
- platform: template
  sensors:
    kitchen_avg_temp:
      friendly_name: "Kitchen Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ (states('sensor.kitchen_motion_sensor_temperature')|float | round(2)) }}

# -- Basement -- only one sensor currently
- platform: template
  sensors:
    basement_avg_temp:
      friendly_name: "Basement Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ (states('sensor.laundry_motion_sensor_temperature')|float | round(2)) }}

# -- Basement Office -- only one sensor currently
- platform: template
  sensors:
    basement_office_avg_temp:
      friendly_name: "Basement Office Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ (states('sensor.basement_office_motion_sensor_temperature')|float | round(2)) }}



##################################
##### Critical Device Status #####
##################################

- platform: template
  sensors:
    mac_mini_server:
      value_template: "{% if states.device_tracker.mac_mini_server %}
      {% if is_state('device_tracker.mac_mini_server', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Mac Mini Server'
    synology_nas:
      value_template: "{% if states.device_tracker.synology_nas %}
      {% if is_state('device_tracker.synology_nas', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Synology NAS'
    kitchen_tablet:
      value_template: "{% if states.device_tracker.nexus_9 %}
      {% if is_state('device_tracker.nexus_9', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Kitchen Tablet'
    hdhomerun_extend:
      value_template: "{% if states.device_tracker.hdhomerun_extend %}
      {% if is_state('device_tracker.hdhomerun_extend', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'HDHomeRun Extend'
    logitech_harmony_hub:
      value_template: "{% if states.device_tracker.logitech_harmony_hub %}
      {% if is_state('device_tracker.logitech_harmony_hub', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Logitech Harmony Hub'
    yamaha_reciever:
      value_template: "{% if states.device_tracker.yamaha_rx_v675 %}
      {% if is_state('device_tracker.yamaha_rx_v675', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Yamaha Receiver'
    rear_porch_camera:
      value_template: "{% if states.device_tracker.rear_porch_camera %}
      {% if is_state('device_tracker.rear_porch_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Rear Porch Camera'
      icon_template: mdi:cctv
    front_door_camera:
      value_template: "{% if states.device_tracker.front_door_camera %}
      {% if is_state('device_tracker.front_door_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Front Door Camera'
      icon_template: mdi:cctv
    garage_camera:
      value_template: "{% if states.device_tracker.garage_camera %}
      {% if is_state('device_tracker.garage_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Garage Camera'
      icon_template: mdi:cctv
    doorbell_camera:
      value_template: "{% if states.device_tracker.doorbell %}
      {% if is_state('device_tracker.doorbell', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Doorbell Camera'
      icon_template: mdi:cctv
    living_room_camera:
      value_template: "{% if states.device_tracker.living_room_camera %}
      {% if is_state('device_tracker.living_room_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Living Room Camera'
      icon_template: mdi:cctv

###################
##### Energy #####
##################
- platform: integration
  name: Server Closet Energy
  source: sensor.server_closet_power
  method: left
  unit: kWh

- platform: integration
  name: Tesla Energy
  source: sensor.tesla_charger_power_home
  method: left
  unit: kWh

- platform: template
  sensors:
    tesla_charger_power_home:
      friendly_name: 'Tesla Charger Power Home'
      icon_template: mdi:lightning-bolt
      unit_of_measurement: "kW"
      value_template: >-
        {% if is_state('sensor.tesla_geofence', 'Home') %}
          {{ states.sensor.tesla_charger_power.state }}
        {% else %}
          0
        {% endif %}
  
##################################
##### Tesla / Teslamate MQTT #####
##################################


- platform: template
  sensors:
    tesla_est_battery_range_mi:
      friendly_name: Estimated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (states('sensor.tesla_est_battery_range_km') | float / 1.609) | round(2) }}

    tesla_rated_battery_range_mi:
      friendly_name: Rated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (states('sensor.tesla_rated_battery_range_km') | float / 1.609) | round(2) }}

    tesla_ideal_battery_range_mi:
      friendly_name: Ideal Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (states('sensor.tesla_ideal_battery_range_km') | float / 1.609) | round(2) }}

    tesla_odometer_mi:
      friendly_name: Odometer (mi)
      unit_of_measurement: mi
      icon_template: mdi:counter
      value_template: >
        {{ (states('sensor.tesla_odometer') | float / 1.609) | round(2) }}

    tesla_speed_mph:
      friendly_name: Speed (MPH)
      unit_of_measurement: mph
      icon_template: mdi:speedometer
      value_template: >
        {{ (states('sensor.tesla_speed') | float / 1.609) | round(2) }}

- platform: mqtt
  name: tesla_state
  state_topic: "teslamate/cars/1/state"
  icon: mdi:car-connected

- platform: mqtt
  name: tesla_since
  state_topic: "teslamate/cars/1/since"
  icon: mdi:clock-outline

- platform: mqtt
  name: tesla_healthy
  state_topic: "teslamate/cars/1/healthy"
  icon: mdi:heart-pulse

- platform: mqtt
  name: tesla_version
  state_topic: "teslamate/cars/1/version"
  icon: mdi:alphabetical

- platform: mqtt
  name: tesla_update_available
  state_topic: "teslamate/cars/1/update_available"
  icon: mdi:alarm

- platform: mqtt
  name: tesla_update_version
  state_topic: "teslamate/cars/1/update_version"
  icon: mdi:alphabetical

- platform: mqtt
  name: tesla_geofence
  state_topic: "teslamate/cars/1/geofence"
  icon: mdi:earth

- platform: mqtt
  name: tesla_latitude
  state_topic: "teslamate/cars/1/latitude"
  icon: mdi:crosshairs-gps

- platform: mqtt
  name: tesla_longitude
  state_topic: "teslamate/cars/1/longitude"
  icon: mdi:crosshairs-gps

- platform: mqtt
  name: tesla_locked
  state_topic: "teslamate/cars/1/locked"
  icon: mdi:lock

- platform: mqtt
  name: tesla_sentry_mode
  state_topic: "teslamate/cars/1/sentry_mode"
  icon: mdi:cctv

- platform: mqtt
  name: tesla_windows_open
  state_topic: "teslamate/cars/1/windows_open"
  icon: mdi:car-door

- platform: mqtt
  name: tesla_doors_open
  state_topic: "teslamate/cars/1/doors_open"
  icon: mdi:car-door

- platform: mqtt
  name: tesla_trunk_open
  state_topic: "teslamate/cars/1/trunk_open"
  icon: mdi:car-side

- platform: mqtt
  name: tesla_frunk_open
  state_topic: "teslamate/cars/1/frunk_open"
  icon: mdi:car-side

- platform: mqtt
  name: tesla_is_user_present
  state_topic: "teslamate/cars/1/is_user_present"
  icon: mdi:human-greeting

- platform: mqtt
  name: tesla_is_climate_on
  state_topic: "teslamate/cars/1/is_climate_on"
  icon: mdi:fan

- platform: mqtt
  name: tesla_inside_temp
  state_topic: "teslamate/cars/1/inside_temp"
  unit_of_measurement: °C
  icon: mdi:thermometer-lines

- platform: mqtt
  name: tesla_outside_temp
  state_topic: "teslamate/cars/1/outside_temp"
  unit_of_measurement: °C
  icon: mdi:thermometer-lines

- platform: mqtt
  name: tesla_is_preconditioning
  state_topic: "teslamate/cars/1/is_preconditioning"
  icon: mdi:fan

- platform: mqtt
  name: tesla_odometer
  state_topic: "teslamate/cars/1/odometer"
  unit_of_measurement: km
  icon: mdi:counter

- platform: mqtt
  name: tesla_est_battery_range_km
  state_topic: "teslamate/cars/1/est_battery_range_km"
  unit_of_measurement: "km"
  icon: mdi:gauge

- platform: mqtt
  name: tesla_rated_battery_range_km
  state_topic: "teslamate/cars/1/rated_battery_range_km"
  unit_of_measurement: "km"
  icon: mdi:gauge

- platform: mqtt
  name: tesla_ideal_battery_range_km
  state_topic: "teslamate/cars/1/ideal_battery_range_km"
  unit_of_measurement: "km"
  icon: mdi:gauge

- platform: mqtt
  name: tesla_battery_level
  state_topic: "teslamate/cars/1/battery_level"
  unit_of_measurement: "%"
  icon: mdi:battery-80
  
- platform: mqtt
  name: tesla_usable_battery_level
  state_topic: "teslamate/cars/1/usable_battery_level"
  unit_of_measurement: "%"
  icon: mdi:battery-80

- platform: mqtt
  name: tesla_plugged_in
  state_topic: "teslamate/cars/1/plugged_in"
  icon: mdi:ev-station

- platform: mqtt
  name: tesla_charge_energy_added
  state_topic: "teslamate/cars/1/charge_energy_added"
  unit_of_measurement: "kWh"
  icon: mdi:battery-charging

- platform: mqtt
  name: tesla_charge_limit_soc
  state_topic: "teslamate/cars/1/charge_limit_soc"
  unit_of_measurement: "%"
  icon: mdi:battery-charging-100

- platform: mqtt
  name: tesla_charge_port_door_open
  state_topic: "teslamate/cars/1/charge_port_door_open"
  icon: mdi:ev-plug-tesla

- platform: mqtt
  name: tesla_charger_actual_current
  state_topic: "teslamate/cars/1/charger_actual_current"
  unit_of_measurement: "A"
  icon: mdi:lightning-bolt

- platform: mqtt
  name: tesla_charger_power
  state_topic: "teslamate/cars/1/charger_power"
  icon: mdi:lightning-bolt
  unit_of_measurement: "kW"

- platform: mqtt
  name: tesla_charger_voltage
  state_topic: "teslamate/cars/1/charger_voltage"
  unit_of_measurement: "V"
  icon: mdi:lightning-bolt

- platform: mqtt
  name: tesla_scheduled_charging_start_time
  state_topic: "teslamate/cars/1/scheduled_charging_start_time"
  icon: mdi:clock-outline

- platform: mqtt
  name: tesla_time_to_full_charge
  state_topic: "teslamate/cars/1/time_to_full_charge"
  unit_of_measurement: "h"
  icon: mdi:clock-outline