- platform: sonarr
  api_key: !secret sonarr_api
  host: !secret sonarr_ip
  port: !secret sonarr_port
  monitored_conditions:
    - upcoming
  days: 7
- platform: radarr
  api_key: !secret radarr_api
  host: !secret radarr_ip
  port: !secret radarr_port
  monitored_conditions:
    - upcoming
    - diskspace
  days: 7
- platform: tautulli
  api_key: !secret tautulli_api
  host: !secret tautulli_ip
- platform: template
  sensors:
    ryan_status:
      value_template: '{{ states.variable.ryan_status.state }}'
      friendly_name: 'Ryan'
    kelly_status:
      value_template: '{{ states.variable.kelly_status.state }}'
      friendly_name: 'Kelly'

# Climate.thermostat doesn't demonstration changes to the preset_mode in the logbook or history
- platform: template
  sensors:
    ecobee_preset:
      value_template: '{{ states.climate.thermostat.attributes.preset_mode }}'
      friendly_name: "Ecobee Preset"
  
  
- platform: template
  sensors:
    bedroom_avg_temp:
      friendly_name: "Bedroom Temperature"
      unit_of_measurement: '째F'
      value_template: >-
        {{ ((float(states.sensor.bedroom_fan_button_temperature.state) + float(states.sensor.bedroom_light_button_temperature.state))  / 2)  | round(2) }}

# Harmony Remote sensor for current activity
- platform: template
  sensors:
      harmony_hub_activity:
        value_template: '{{ state_attr("remote.harmony_hub", "current_activity") }}'
        friendly_name: 'Media Room'

## Folder for mp4 videos
- platform: folder
  folder: /tmp/hass


## Smart Things Button Pushes
- platform: mqtt
  name: Bedroom Fan Button
  state_topic: "smartthings/Fan Button/button"
  expire_after: 1
## Smart Things Button Temperature
- platform: mqtt
  name: Bedroom Fan Button Temperature
  state_topic: "smartthings/Fan Button/temperature"
  unit_of_measurement: '째F'
## Smart Things Button Battery
- platform: mqtt
  name: Bedroom Fan Button Battery
  state_topic: "smartthings/Fan Button/battery"
  unit_of_measurement: '%'

## Smart Things Button Pushes
- platform: mqtt
  name: Bedroom Light Button
  state_topic: "smartthings/Bedroom Light Button/button"
  expire_after: 1
## Smart Things Button Temperature
- platform: mqtt
  name: Bedroom Light Button Temperature
  state_topic: "smartthings/Bedroom Light Button/temperature"
  unit_of_measurement: '째F'
## Smart Things Button Battery
- platform: mqtt
  name: Bedroom Light Button Battery
  state_topic: "smartthings/Bedroom Light Button/battery"
  unit_of_measurement: '%'

## Smart Things Kitchen Motion Sensor
- platform: mqtt
  name: Kitchen Motion Sensor
  state_topic: "smartthings/Kitchen Motion Sensor/motion"
## Smart Things Kitchen Motion Sensor
- platform: mqtt
  name: Kitchen Motion Sensor Temperature
  state_topic: "smartthings/Kitchen Motion Sensor/temperature"
  unit_of_measurement: '째F'
## Smart Things Kitchen Motion Sensor
- platform: mqtt
  name: Kitchen Motion Sensor Battery
  state_topic: "smartthings/Kitchen Motion Sensor/battery"
  unit_of_measurement: '%'


#### Integral device status ##########
- platform: template
  sensors:
    hue_bridge:
      value_template: "{% if states.device_tracker.hue_bridge %}
      {% if is_state('device_tracker.hue_bridge', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Hue Bridge'
    smartthings_hub:
      value_template: "{% if states.device_tracker.samsung_smartthings_hub_ethernet %}
      {% if is_state('device_tracker.samsung_smartthings_hub_ethernet', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'SmartThings Hub'
    synology_nas:
      value_template: "{% if states.device_tracker.synology_nas %}
      {% if is_state('device_tracker.synology_nas', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Synology NAS'
    kitchen_tablet:
      value_template: "{% if states.device_tracker.nexus_9 %}
      {% if is_state('device_tracker.nexus_9', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Kitchen Tablet'
    hdhomerun_extend:
      value_template: "{% if states.device_tracker.hdhomerun_extend %}
      {% if is_state('device_tracker.hdhomerun_extend', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'HDHomeRun Extend'
    logitech_harmony_hub:
      value_template: "{% if states.device_tracker.logitech_harmony_hub %}
      {% if is_state('device_tracker.logitech_harmony_hub', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Logitech Harmony Hub'
    yamaha_reciever:
      value_template: "{% if states.device_tracker.yamaha_rx_v675 %}
      {% if is_state('device_tracker.yamaha_rx_v675', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Yamaha Receiver'
    rear_porch_camera:
      value_template: "{% if states.device_tracker.uvc_g3_flex_d1c0 %}
      {% if is_state('device_tracker.uvc_g3_flex_d1c0', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Rear Porch Camera'
      icon_template: mdi:cctv
    front_door_camera:
      value_template: "{% if states.device_tracker.front_door_camera %}
      {% if is_state('device_tracker.front_door_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Front Door Camera'
      icon_template: mdi:cctv
    garage_camera:
      value_template: "{% if states.device_tracker.garage_camera %}
      {% if is_state('device_tracker.garage_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Garage Camera'
      icon_template: mdi:cctv
