####################################
####### SENSOR CONFIGURATION  ######
####################################

- platform: radarr
  api_key: !secret radarr_api
  host: !secret radarr_ip
  port: !secret radarr_port
  days: 7
- platform: tautulli
  api_key: !secret tautulli_api
  host: !secret tautulli_ip
- platform: template
  sensors:
    ryan_status:
      value_template: '{{ states.variable.ryan_status.state }}'
      friendly_name: 'Ryan'
    kelly_status:
      value_template: '{{ states.variable.kelly_status.state }}'
      friendly_name: 'Kelly'

# Climate.thermostat doesn't demonstration changes to the preset_mode in the logbook or history
- platform: template
  sensors:
    ecobee_preset:
      value_template: '{{ states.climate.thermostat.attributes.preset_mode }}'
      friendly_name: "Ecobee Preset"
  
  

# Temperature for rooms
# Define below multiple sensors into one, only rely on these sensors for automations and views

#  -- Bedroom --
- platform: template
  sensors:
    bedroom_avg_temp:
      friendly_name: "Bedroom Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.ryans_bedside_button_temperature.state) + float(states.sensor.bedroom_light_button_temperature.state))  / 2)  | round(2) }}

#  -- Living Room --
- platform: template
  sensors:
    living_room_avg_temp:
      friendly_name: "Living Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.living_room_temperature.state) + float(states.sensor.thermostat_temperature.state))  / 2)  | round(2) }}

# -- Media Room -- only one sensor currently
- platform: template
  sensors:
    media_room_avg_temp:
      friendly_name: "Media Room Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ (float(states.sensor.media_room_temperature.state) | round(2)) }}
        
# -- Kitchen -- only one sensor currently
- platform: template
  sensors:
    kitchen_avg_temp:
      friendly_name: "Kitchen Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ (float(states.sensor.kitchen_motion_sensor_temperature.state) | round(2)) }}

# -- Basement -- only one sensor currently
- platform: template
  sensors:
    basement_avg_temp:
      friendly_name: "Basement Temperature"
      unit_of_measurement: '°F'
      value_template: >-
        {{ (float(states.sensor.laundry_motion_sensor_temperature.state) | round(2)) }}



# Harmony Remote sensor for current activity
- platform: template
  sensors:
      harmony_hub_activity:
        value_template: '{{ state_attr("remote.harmony_hub", "current_activity") }}'
        friendly_name: 'Media Room'

## Folder for mp4 videos
- platform: folder
  folder: /tmp/hass
    
# Bhyve sensor (water/garden)
- platform: bhyve

#### Integral device status ##########
- platform: template
  sensors:
    mac_mini_server:
      value_template: "{% if states.device_tracker.mac_mini_server %}
      {% if is_state('device_tracker.mac_mini_server', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Mac Mini Server'
    synology_nas:
      value_template: "{% if states.device_tracker.synology_nas %}
      {% if is_state('device_tracker.synology_nas', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Synology NAS'
    kitchen_tablet:
      value_template: "{% if states.device_tracker.nexus_9 %}
      {% if is_state('device_tracker.nexus_9', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Kitchen Tablet'
    hdhomerun_extend:
      value_template: "{% if states.device_tracker.hdhomerun_extend %}
      {% if is_state('device_tracker.hdhomerun_extend', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'HDHomeRun Extend'
    logitech_harmony_hub:
      value_template: "{% if states.device_tracker.logitech_harmony_hub %}
      {% if is_state('device_tracker.logitech_harmony_hub', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Logitech Harmony Hub'
    yamaha_reciever:
      value_template: "{% if states.device_tracker.yamaha_rx_v675 %}
      {% if is_state('device_tracker.yamaha_rx_v675', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Yamaha Receiver'
    rear_porch_camera:
      value_template: "{% if states.device_tracker.rear_porch_camera %}
      {% if is_state('device_tracker.rear_porch_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Rear Porch Camera'
      icon_template: mdi:cctv
    front_door_camera:
      value_template: "{% if states.device_tracker.front_door_camera %}
      {% if is_state('device_tracker.front_door_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Front Door Camera'
      icon_template: mdi:cctv
    garage_camera:
      value_template: "{% if states.device_tracker.garage_camera %}
      {% if is_state('device_tracker.garage_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Garage Camera'
      icon_template: mdi:cctv
    doorbell_camera:
      value_template: "{% if states.device_tracker.doorbell_camera %}
      {% if is_state('device_tracker.doorbell_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Doorbell Camera'
      icon_template: mdi:cctv
    living_room_camera:
      value_template: "{% if states.device_tracker.living_room_camera %}
      {% if is_state('device_tracker.living_room_camera', 'home') %}
        Online
      {% else %}
        Offline
      {% endif %}
      {% else %}
        Unknown
      {% endif %}"
      friendly_name: 'Living Room Camera'
      icon_template: mdi:cctv
