####################################
####### BINARY_SENSOR DOORS   ######
####################################

- platform: group
  name: House Doors
  unique_id: house_doors
  entities:
    - binary_sensor.ryans_office_doors
    - binary_sensor.living_room_doors
    - binary_sensor.kitchen_doors
    - binary_sensor.family_room_doors
    - binary_sensor.laundry_room_doors

- platform: group
  name: Exterior Doors
  unique_id: exterior_doors
  entities:
    - binary_sensor.front_door_sensor
    - binary_sensor.porch_slider_sensor
    - binary_sensor.family_room_slider
    - binary_sensor.basement_door_sensor

# - platform: group
#   name: Kellys Office Doors
#   entities:
#     - binary_sensor.sample_window_sensor

- platform: group
  name: Ryans Office Doors
  unique_id: ryans_office_doors
  entities:
    - binary_sensor.ryans_office_door_sensor

# - platform: group
#   name: Master Bedroom Doors
#   entities:
#     - binary_sensor.sample_window_sensor

# - platform: group
#   name: Guest Room Doors
#   entities:
#     - binary_sensor.sample_window_sensor

- platform: group
  name: Living Room Doors
  unique_id: living_room_doors
  entities:
    - binary_sensor.front_door_sensor

- platform: group
  name: Kitchen Doors
  unique_id: kitchen_doors
  entities:
    - binary_sensor.porch_slider_sensor

- platform: group
  name: Family Room Doors
  unique_id: family_room_doors
  entities:
    - binary_sensor.family_room_slider

- platform: group
  name: Laundry Room Doors
  unique_id: laundry_room_doors
  entities:
    - binary_sensor.basement_door_sensor